package surfaces;

import basis.EveningsEvent;
import basis.Guest;
import control.Control;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 *
 * @author KissJGabi
 */
public class JubileePanel extends javax.swing.JPanel {

    private Control control;
    private DefaultListModel<EveningsEvent> eventsModel = new DefaultListModel<>();
    private DefaultListModel<Guest> guestsModel = new DefaultListModel<>();
    private DefaultListModel<String> incomMaxModel = new DefaultListModel<>();
    private DefaultListModel<String> visitedEventsModel = new DefaultListModel<>();

    private final String MAX_LABEL_TXT = "A legnagyobb bevételű rendezvények: ";

    public JubileePanel() {
        initComponents();
        lstEvents.setModel(eventsModel);
        lstGuests.setModel(guestsModel);
        lstIncomeMax.setModel(incomMaxModel);
        lstVisitedEvents.setModel(visitedEventsModel);
        lblIncomeMax.setText(MAX_LABEL_TXT);
    }

    public void setControl(Control c) {
        this.control = c;
    }

    public void write2list(List<EveningsEvent> eventsList,
            List<Guest> guestsList) {
        eventsList.forEach((eveningsEvent) -> {
            eventsModel.addElement(eveningsEvent);
        });
        guestsList.forEach((guest) -> {
            guestsModel.addElement(guest);
        });
    }

    public void writeMax(List<EveningsEvent> eventsMaxIncome, int max) {
        lblIncomeMax.setText(MAX_LABEL_TXT + max + " Ft-tal:");
        incomMaxModel.clear();
        for (EveningsEvent eveningsEvent : eventsMaxIncome) {
            incomMaxModel.addElement(eveningsEvent.getTitle());
        }
    }

    public void writeOrdered(List<EveningsEvent> eventsList) {
        eventsModel.clear();
        eventsList.forEach((eveningsEvent) -> {
            eventsModel.addElement(eveningsEvent);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstEvents = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstGuests = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstVisitedEvents = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstIncomeMax = new javax.swing.JList<>();
        lblIncomeMax = new javax.swing.JLabel();
        lblVisitedEvents = new javax.swing.JLabel();
        lblIncomeSum = new javax.swing.JLabel();
        btnJubileum = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 500));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jubileum 650");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Rendezvények");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Résztvevők");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(260, 162));

        lstEvents.setModel(new javax.swing.AbstractListModel<EveningsEvent>() {
            EveningsEvent[] e;
            public int getSize() { return e.length; }
            public EveningsEvent getElementAt(int i) { return e[i]; }
        });
        lstEvents.setMaximumSize(new java.awt.Dimension(300, 200));
        lstEvents.setMinimumSize(new java.awt.Dimension(0, 0));
        lstEvents.setPreferredSize(new java.awt.Dimension(260, 180));
        lstEvents.setVisibleRowCount(10);
        lstEvents.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstEventsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstEvents);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(260, 162));

        lstGuests.setModel(new javax.swing.AbstractListModel<Guest>() {
            Guest[] g;
            public int getSize() { return g.length; }
            public Guest getElementAt(int i) { return g[i]; }
        });
        lstGuests.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstGuests.setMaximumSize(new java.awt.Dimension(300, 200));
        lstGuests.setMinimumSize(new java.awt.Dimension(0, 0));
        lstGuests.setPreferredSize(new java.awt.Dimension(260, 180));
        lstGuests.setVisibleRowCount(10);
        lstGuests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lstGuestsMousePressed(evt);
            }
        });
        lstGuests.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstGuestsValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstGuests);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(260, 130));

        lstVisitedEvents.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstVisitedEvents.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstVisitedEvents.setMaximumSize(new java.awt.Dimension(300, 200));
        lstVisitedEvents.setMinimumSize(new java.awt.Dimension(0, 0));
        lstVisitedEvents.setPreferredSize(new java.awt.Dimension(260, 180));
        jScrollPane3.setViewportView(lstVisitedEvents);

        jScrollPane4.setPreferredSize(new java.awt.Dimension(260, 130));

        lstIncomeMax.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstIncomeMax.setMaximumSize(new java.awt.Dimension(300, 200));
        lstIncomeMax.setMinimumSize(new java.awt.Dimension(0, 0));
        lstIncomeMax.setPreferredSize(new java.awt.Dimension(260, 180));
        jScrollPane4.setViewportView(lstIncomeMax);

        lblIncomeMax.setText("A legmagasabb bevételű rendezvények:");

        lblVisitedEvents.setText("XY által látogatott rendezvények:");

        lblIncomeSum.setText("A kijelölt rendezvények összes bevétele:");

        btnJubileum.setText("Imitate jubileum");
        btnJubileum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJubileumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIncomeSum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIncomeMax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVisitedEvents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnJubileum)
                        .addGap(90, 90, 90))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(lblIncomeMax)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVisitedEvents)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJubileum)
                    .addComponent(lblIncomeSum))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnJubileumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJubileumActionPerformed
        control.imitateJubileum();
        control.getMaxIncome();
        control.sortEventsList();
        btnJubileum.setEnabled(false);
    }//GEN-LAST:event_btnJubileumActionPerformed

    private void lstEventsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstEventsValueChanged
        List<EveningsEvent> selected = lstEvents.getSelectedValuesList();
        lblIncomeSum.setText(String.
                format("A kijelölt rendezvények összes bevétele: %d Ft",
                        control.sumSelected(selected)));
    }//GEN-LAST:event_lstEventsValueChanged

    private void lstGuestsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstGuestsMousePressed
        Guest guest = (Guest) lstGuests.getSelectedValue();
        lblVisitedEvents.setText(guest.getName()
                + " által látogatott rendezvények: ");
        visitedEventsModel.clear();
        for (EveningsEvent eveningsEvent : guest.getEventsList()) {
            visitedEventsModel.addElement(eveningsEvent.getTitle());
        }
    }//GEN-LAST:event_lstGuestsMousePressed

    private void lstGuestsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstGuestsValueChanged
        Guest guest = (Guest) lstGuests.getSelectedValue();
        lblVisitedEvents.setText(guest.getName()
                + " által látogatott rendezvények: ");
        visitedEventsModel.clear();
        for (EveningsEvent eveningsEvent : guest.getEventsList()) {
            visitedEventsModel.addElement(eveningsEvent.getTitle());
        }
    }//GEN-LAST:event_lstGuestsValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJubileum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblIncomeMax;
    private javax.swing.JLabel lblIncomeSum;
    private javax.swing.JLabel lblVisitedEvents;
    private javax.swing.JList<EveningsEvent> lstEvents;
    private javax.swing.JList<Guest> lstGuests;
    private javax.swing.JList<String> lstIncomeMax;
    private javax.swing.JList<String> lstVisitedEvents;
    // End of variables declaration//GEN-END:variables
}
