package control;

import javax.swing.event.AncestorEvent;

/**
 *
 * @author KissJGabi
 */
public class MainFrame extends javax.swing.JFrame {

    private final int PANEL_WIDTH = 816;
    private final int PANEL_HEIGHT = 588;
    private final String PANEL_TITLE = "Foci EB";

    public MainFrame() {
        initComponents();
        super.setSize(PANEL_WIDTH, PANEL_HEIGHT);
        super.setTitle(PANEL_TITLE);
        super.setLocationRelativeTo(null);
        jTabbedPane1.setTitleAt(2, "Megnézett meccsek");
    }

    private void start() {
        setVisible(true);
        Control c = new Control(matchPanel1, viewedMatchesPanel1);
        matchPanel1.setControl(c);
        viewedMatchesPanel1.setControl(c);
        c.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        regulationPanel1 = new surface.RegulationPanel();
        matchPanel1 = new surface.MatchPanel();
        viewedMatchesPanel1 = new surface.ViewedMatchesPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("tabbedFrame1"); // NOI18N

        jTabbedPane1.addTab("Szabályzat", regulationPanel1);
        jTabbedPane1.addTab("Mérkőzés", matchPanel1);
        jTabbedPane1.addTab("Archívum", viewedMatchesPanel1);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().start();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private surface.MatchPanel matchPanel1;
    private surface.RegulationPanel regulationPanel1;
    private surface.ViewedMatchesPanel viewedMatchesPanel1;
    // End of variables declaration//GEN-END:variables
}
