/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aSurface;

import aBasis.Article;
import aBasis.Messenger;
import aControl.Control;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author b6dmin
 */
public class Media3Panel extends javax.swing.JPanel {

    private DefaultListModel<Article> articleListModel
            = new DefaultListModel<>();

    private Control c;

    private int index = 0;

    /**
     * Creates new form Media3panel
     */
    public Media3Panel() {
        initComponents();
        lstArticles.setModel(articleListModel);
    }

    public void setControl(Control c) {
        this.c = c;
    }

    public void resetDisplay() {
        articleListModel.clear();
        buttonGroup1.clearSelection();
    }

    public void listArticles(List<Article> list) {
        articleListModel.clear();
        for (Article article : list) {
            articleListModel.addElement(article);
        }
        lstArticles.repaint();
    }

    public void listAllNews(List<Messenger> newsList) {
        JRadioButton rdButton;
        JLabel label;

        int distance_h = 10, distance_v = 20;
        int gap = 40;
        int rdButtonWidth = 300;
        int rdButtonHeight = 20;

        int labelDistance_h = 350;
        int labelWidth = 100;
        int labelHeight = 20;

        int scrollBarWidth = 21;

        for (int ii = 0; ii < newsList.size(); ii++) {
            rdButton = new JRadioButton(newsList.get(ii).toString());
            rdButton.setLocation(distance_h, distance_v + ii * gap);
            rdButton.setSize(rdButtonWidth, rdButtonHeight);
            rdButton.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    index = (((JRadioButton) e.getSource()).getY()
                            - distance_v) / gap;
                    c.showArticles(index);
                }
            });
            this.pnlBackground.add(rdButton);
            buttonGroup1.add(rdButton);

            label = new JLabel(newsList.get(ii).toString());
            label.setLocation(labelDistance_h, distance_v + ii * gap);
            label.setSize(labelWidth, labelHeight);
            this.pnlBackground.add(label);
        }
        Dimension preferredSize
                = new Dimension(lstMessengers.getWidth() - scrollBarWidth,
                        newsList.size() * gap + distance_v);
        pnlBackground.setPreferredSize(preferredSize);
        validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstArticles = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblLieOfArticle = new javax.swing.JLabel();
        btnDeletarticle = new javax.swing.JButton();
        lstMessengers = new javax.swing.JScrollPane();
        pnlBackground = new javax.swing.JPanel();

        setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Újságok");

        lstArticles.setModel(new javax.swing.AbstractListModel<Article>() {
            Article[] a;
            public int getSize() { return a.length; }
            public Article getElementAt(int i) { return a[i]; }
        });
        lstArticles.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstArticles.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstArticlesValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstArticles);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cikkek");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Választott cikk");

        lblLieOfArticle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLieOfArticle.setText("hazugság: ");

        btnDeletarticle.setText("Töröl");
        btnDeletarticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarticleActionPerformed(evt);
            }
        });

        lstMessengers.setPreferredSize(new java.awt.Dimension(280, 380));

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );

        lstMessengers.setViewportView(pnlBackground);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lstMessengers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLieOfArticle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeletarticle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblLieOfArticle)
                        .addGap(89, 89, 89)
                        .addComponent(btnDeletarticle))
                    .addComponent(lstMessengers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lstArticlesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstArticlesValueChanged
        if (lstArticles.getSelectedValue() != null) {
            lblLieOfArticle.setText("hazugság "
                    + lstArticles.getSelectedValue().getLIE_PROPORTION() + "%");
        }
    }//GEN-LAST:event_lstArticlesValueChanged

    private void btnDeletarticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarticleActionPerformed
        c.removeArticle(index, lstArticles.getSelectedValue());
    }//GEN-LAST:event_btnDeletarticleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletarticle;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLieOfArticle;
    private javax.swing.JList<Article> lstArticles;
    private javax.swing.JScrollPane lstMessengers;
    private javax.swing.JPanel pnlBackground;
    // End of variables declaration//GEN-END:variables
}
