/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aSurface;

import aBasis.InetNews;
import aBasis.Messenger;
import aControl.Control;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author b6dmin
 */
public class SummaryPanel extends javax.swing.JPanel {

    private DefaultTableModel summaryModel = new DefaultTableModel();
    private long liePropotion;

    private Control control;

    public void setControl(Control c) {
        this.control = c;
    }

    /**
     * Creates new form SummaryPanel
     */
    public SummaryPanel() {
        initComponents();
        tblStatement.setShowGrid(true);
        summaryModel = (DefaultTableModel) tblStatement.getModel();
    }

    public void summaryTable(List<Messenger> list) {
        liePropotion = 0;
        int n = 0;
        int x = this.summaryModel.getRowCount();
        for (int ii = x - 1; ii >= 0; ii--) {
            this.summaryModel.removeRow(ii);
        }//a törlés föntről indul!!
        for (Messenger m : list) {
            Object[] tableRow = new Object[4];
            tableRow[0] = m.getNAME();
            tableRow[1] = m.getDATE();
            tableRow[2] = m.getArticleNumbers();
            if (m instanceof InetNews) {
                tableRow[3] = "internetes";
            } else {
                tableRow[3] = "nyomtatott";
            }
            this.summaryModel.addRow(tableRow);
            liePropotion += m.getSumOfLies();
            n += m.getArticleNumbers();
        }
        if (n == 0) {
            lblLiePercent.setText("A médiabirodalom nem jelentetett meg cikket!");
        } else {
            lblLiePercent.setText("A médiabirodalom átlagos hazugsága: "
                    + liePropotion / n + " %");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStatement = new javax.swing.JTable();
        lblLiePercent = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 500));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KIMUTATÁS");

        tblStatement.setAutoCreateRowSorter(true);
        tblStatement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Újságcím", "Dátum", "Cikkek száma", "Nyomtatott/Internetes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStatement.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblStatement);
        if (tblStatement.getColumnModel().getColumnCount() > 0) {
            tblStatement.getColumnModel().getColumn(0).setResizable(false);
            tblStatement.getColumnModel().getColumn(1).setResizable(false);
            tblStatement.getColumnModel().getColumn(2).setResizable(false);
            tblStatement.getColumnModel().getColumn(3).setResizable(false);
        }

        lblLiePercent.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLiePercent.setText("A médiabirodalom átlagos hazugsága:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(lblLiePercent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(lblLiePercent)
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLiePercent;
    private javax.swing.JTable tblStatement;
    // End of variables declaration//GEN-END:variables
}
