/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aSurface;

import static aBasis.Global.*;
import aBasis.Sprite;
import aControl.Control;
import java.awt.Dimension;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author b6dmin
 */
public class ControlPanel extends javax.swing.JPanel {

    private Control c;

    public void setControl(Control c) {
        this.c = c;
    }

    private String comboSelected;

    public void setup() {
        System.out.println("controlPanel: "
                + this.getWidth() + "x" + this.getHeight());
        setButtonActivity(false);
    }

    private final DefaultComboBoxModel<String> comboModel;
    private final DefaultListModel<Sprite> listModel;

    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {
        this.comboModel = new DefaultComboBoxModel<>();
        this.listModel = new DefaultListModel<>();
        System.out.println("controlPanel()");
        initComponents();
        super.setPreferredSize(new Dimension(CONTROL_WIDTH, CONTROL_HEIGHT));
        lblTitle.setText(CONTROL_LBL_TITLE);
        lblChoose.setText(CONTROL_LBL_CHOOSE);
        btnOrder.setText(CONTROL_BTN_ORDER);
        lblBill.setText(CONTROL_LBL_BILL);
        btnFinish.setText(CONTROL_BTN_FINISH);
        btnSave.setText(CONTROL_BTN_SAVE);
        comboOrder.setModel(comboModel);
        lstBill.setModel(listModel);
    }

    public void setButtonOrder(boolean b) {
        btnOrder.setEnabled(b);
    }

    public void setButtonFinish(boolean b) {
        btnFinish.setEnabled(b);
    }

    public void setButtonSave(boolean b) {
        btnSave.setEnabled(b);
    }

    public void setButtonActivity(boolean b) {
        setButtonOrder(b);
        setButtonFinish(b);
        setButtonSave(b);
    }

    public void addSprite(Sprite s) {
        listModel.addElement(s);
    }

    public void deleteSprite(Sprite old) {
        if (listModel.contains(old)) {
            listModel.removeElement(old);
        }
    }

    public void addBlock(String s) {
        comboModel.addElement(s);
    }

    public void resetConboBox() {
        comboModel.setSelectedItem(CONTROL_CHOOSE_TXT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnFinish = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstBill = new javax.swing.JList<>();
        lblBill = new javax.swing.JLabel();
        lblChoose = new javax.swing.JLabel();
        comboOrder = new javax.swing.JComboBox<>();
        btnOrder = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 51));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("jLabel1");

        btnSave.setText("jButton1");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnFinish.setText("jButton1");
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });

        lstBill.setModel(new javax.swing.AbstractListModel<Sprite>() {
            Sprite[] s = { };
            public int getSize() { return s.length; }
            public Sprite getElementAt(int i) { return s[i]; }
        });
        jScrollPane1.setViewportView(lstBill);

        lblBill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBill.setForeground(new java.awt.Color(255, 255, 255));
        lblBill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBill.setText("jLabel1");

        lblChoose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblChoose.setForeground(new java.awt.Color(255, 255, 255));
        lblChoose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChoose.setText("jLabel1");

        comboOrder.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboOrder.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboOrderItemStateChanged(evt);
            }
        });

        btnOrder.setText("jButton1");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFinish, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBill, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblChoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboOrder, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(lblChoose)
                .addGap(18, 18, 18)
                .addComponent(comboOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(lblBill)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFinish)
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        c.finishProlog();
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        c.startMainProcess();
    }//GEN-LAST:event_btnFinishActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void comboOrderItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboOrderItemStateChanged
        String item = (String) evt.getItem();
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            System.out.println("comboSelected: " + comboSelected);
            System.out.println("item: " + item);
            if (!item.equals(comboSelected)) {
                c.startProlog(item);
            }
        }
        comboSelected = item;
    }//GEN-LAST:event_comboOrderItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinish;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboOrder;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBill;
    private javax.swing.JLabel lblChoose;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<Sprite> lstBill;
    // End of variables declaration//GEN-END:variables
}
