/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aControl;

import aBasis.Book;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author b6dmin
 */
public class MainFrame extends javax.swing.JFrame {

    private final String FRAME_TITLE = "Age Of Books - The Great Library";

    private Control c;
    public boolean LOADED = false;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        super.setTitle(FRAME_TITLE);
        super.setLocationRelativeTo(null);
    }

    public void enableStoragePanel(boolean enable) {
        jTabbedPane1.setEnabledAt(1, enable);
    }

    public void setTextLocale(ResourceBundle bundle) {
        jTabbedPane1.setTitleAt(0, bundle.getString("TAB_0_NAME"));
        jTabbedPane1.setTitleAt(1, bundle.getString("TAB_1_NAME"));
        jTabbedPane1.setTitleAt(2, bundle.getString("TAB_2_NAME"));
    }

    private void start() {
        enableStoragePanel(false);
        this.setVisible(true);
        c = new Control(bookList1, storage1, languages1, this);
        bookList1.setControl(c);
        storage1.setControl(c);
        languages1.setControl(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        bookList1 = new aSurface.BookList();
        storage1 = new aSurface.Storage();
        languages1 = new aSurface.Languages();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jTabbedPane1.addTab("Kölcsönzés", bookList1);
        jTabbedPane1.addTab("Raktár", storage1);
        jTabbedPane1.addTab("Nyelvek", languages1);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        switch (jTabbedPane1.getSelectedIndex()) {
            case 0: {
                System.out.println("tabbedPanel state changed: 0");
                if (LOADED) {
                    c.listBooks();
                }
                break;
            }
            case 1: {
                System.out.println("tabbedPanel state changed: 1");
                c.listStorage();
                break;
            }
            default: {
                System.out.println("tabbedPanel state changed: default");
            }
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().start();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private aSurface.BookList bookList1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private aSurface.Languages languages1;
    private aSurface.Storage storage1;
    // End of variables declaration//GEN-END:variables
}
