CREATE TABLE KATONAK ( id int not null primary key, nev varchar(40), rang varchar(40))
INSERT INTO KATONAK VALUES(1,'Kinizsi Pál','lovas parancsnok')
INSERT INTO KATONAK VALUES(2,'Lehoczky János','gyalogos parancsnok')
INSERT INTO KATONAK VALUES(3,'Magyar Balázs','gyalogos parancsnok')
INSERT INTO KATONAK VALUES(4,'Báthori István','lovas parancsnok')
INSERT INTO KATONAK VALUES(5,'Jaksics Demeter','lovas parancsnok')
INSERT INTO KATONAK VALUES(6,'Both János','lovas parancsnok')
INSERT INTO KATONAK VALUES(7,'Mészáros Bálint','lovas')
INSERT INTO KATONAK VALUES(8,'Fekete József','lovas')
INSERT INTO KATONAK VALUES(9,'Molnár Péter','gyalogos')
INSERT INTO KATONAK VALUES(10,'Szabó Tamás','gyalogos')
INSERT INTO KATONAK VALUES(11,'Pásztor Attila','lovas')
INSERT INTO KATONAK VALUES(12,'Bodnár Béla','lovas')
INSERT INTO KATONAK VALUES(13,'Deák Gergely','gyalogos')
INSERT INTO KATONAK VALUES(14,'Borissza Lajos','gyalogos')
INSERT INTO KATONAK VALUES(15,'Hajdú Géza','lovas')
INSERT INTO KATONAK VALUES(16,'Major Máté','gyalogos')
INSERT INTO KATONAK VALUES(17,'Kovács Kálmán','gyalogos')
INSERT INTO KATONAK VALUES(18,'Vékony Levente','gyalogos')
INSERT INTO KATONAK VALUES(19,'Lakatos Imre','gyalogos')
INSERT INTO KATONAK VALUES(20,'Csikós István','lovas')
INSERT INTO KATONAK VALUES(21,'Kun László','zaszlos')
INSERT INTO KATONAK VALUES(22,'Sipos Zalán','zaszlos')
INSERT INTO KATONAK VALUES(23,'Varga Keve','zaszlos')