package aSurface;

import aBasis.Applicant;
import aBasis.Competition;
import aControl.Control;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author KissJGabi
 */
public class SimulationPanel extends javax.swing.JPanel {

    private DefaultListModel<Applicant> applicantsListModel
            = new DefaultListModel<>();
    private DefaultListModel<Competition> competitionsListModel
            = new DefaultListModel<>();

    private Control c;

    public void setControl(Control c) {
        this.c = c;
    }

    public SimulationPanel() {
        initComponents();
        lstApplicants.setModel(applicantsListModel);
        lstWon.setModel(competitionsListModel);
    }

    private void clearListsAndLabels() {
        applicantsListModel.clear();
        competitionsListModel.clear();
        lblSum.setText("");
        lblMax.setText("");
    }

    private void clearResults() {
        competitionsListModel.clear();
        lblSum.setText("");
        lblMax.setText("");
    }

    public void inApplicantsList(List<Applicant> list) {
        list.forEach((applicant) -> {
            applicantsListModel.addElement(applicant);
        });
    }

    public void inWonsList(List<Competition> list) {
        list.forEach((competition) -> {
            competitionsListModel.addElement(competition);
        });
    }

    public void setSum(int sum) {
        lblSum.setText("A  kifizetett támogatás összesen: " + sum + " Ft");
    }

    public void setMax(int max) {
        lblMax.setText("A  legnagyobb kifizetés: " + max + " Ft");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLoadFromDB = new javax.swing.JButton();
        btnLoadFromFile = new javax.swing.JButton();
        btnSimulateSemester = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstApplicants = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstWon = new javax.swing.JList<>();
        lblSum = new javax.swing.JLabel();
        lblMax = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pályázók");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nyertes pályázók");
        jLabel2.setMaximumSize(new java.awt.Dimension(280, 17));
        jLabel2.setMinimumSize(new java.awt.Dimension(280, 17));
        jLabel2.setPreferredSize(new java.awt.Dimension(280, 17));

        btnLoadFromDB.setText("input DBase");
        btnLoadFromDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadFromDBActionPerformed(evt);
            }
        });

        btnLoadFromFile.setText("input File");
        btnLoadFromFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadFromFileActionPerformed(evt);
            }
        });

        btnSimulateSemester.setText("Szimuláció");
        btnSimulateSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimulateSemesterActionPerformed(evt);
            }
        });

        jButton4.setText("Elbírálás");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(280, 280));

        lstApplicants.setModel(new javax.swing.AbstractListModel<Applicant>() {
            Applicant[] applicants;
            public int getSize() { return applicants.length; }
            public Applicant getElementAt(int i) { return applicants[i]; }
        });
        jScrollPane1.setViewportView(lstApplicants);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(280, 280));

        lstWon.setModel(new javax.swing.AbstractListModel<Competition>() {
            Competition[] competitions;
            public int getSize() { return competitions.length; }
            public Competition getElementAt(int i) { return competitions[i]; }
        });
        jScrollPane2.setViewportView(lstWon);

        lblSum.setText("A  kifizetett támogatás összesen:");

        lblMax.setText("A legnagyobb kifizetés:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLoadFromDB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnLoadFromFile, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSimulateSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSum, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMax, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLoadFromDB)
                            .addComponent(btnLoadFromFile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimulateSemester)
                            .addComponent(jButton4))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSum))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadFromDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadFromDBActionPerformed
        clearListsAndLabels();
        c.inListDB();
    }//GEN-LAST:event_btnLoadFromDBActionPerformed

    private void btnLoadFromFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadFromFileActionPerformed
        clearListsAndLabels();
        c.inListFile();
    }//GEN-LAST:event_btnLoadFromFileActionPerformed

    private void btnSimulateSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimulateSemesterActionPerformed
        clearResults();
        c.simulateNew();
    }//GEN-LAST:event_btnSimulateSemesterActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        clearResults();
        c.inWonList();
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoadFromDB;
    private javax.swing.JButton btnLoadFromFile;
    private javax.swing.JButton btnSimulateSemester;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMax;
    private javax.swing.JLabel lblSum;
    private javax.swing.JList<Applicant> lstApplicants;
    private javax.swing.JList<Competition> lstWon;
    // End of variables declaration//GEN-END:variables
}
