package surface;

import basis.EveningEvent;
import control.Control;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author KissJGabi
 */
public class EventsPanel extends javax.swing.JPanel {

    private final DefaultListModel<String> EVENTSLIST_MODEL;
    private List<EveningEvent> eveningEvents = new ArrayList<>();

    /**
     * Creates new form EventsPanel
     */
    public EventsPanel() {
        this.EVENTSLIST_MODEL = new DefaultListModel<>();
        initComponents();
        lstEveningEvents.setModel(EVENTSLIST_MODEL);
    }

    public void writeToListBox(List<EveningEvent> eventsList) {
        eveningEvents = eventsList;
        eventsList.forEach((event) -> {
            EVENTSLIST_MODEL.addElement(event.getTitle());
        });
    }

    public void writeToTextBox(List<EveningEvent> eventsList) {
        eventsList.forEach((event) -> {
            txtEveningEvents.append(event.toString());
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstEveningEvents = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEveningEvents = new javax.swing.JTextArea();
        lblStartTime = new javax.swing.JLabel();
        btnSumOfPrice = new javax.swing.JButton();
        lblSumOfPrice = new javax.swing.JLabel();
        lblTicketPrice = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setAlignmentX(0.1F);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rendezvények");
        jLabel1.setMaximumSize(new java.awt.Dimension(118, 44));
        jLabel1.setMinimumSize(new java.awt.Dimension(118, 44));
        jLabel1.setName(""); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(118, 44));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Listafelületen");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Szövegdobozban");

        lstEveningEvents.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstEveningEvents.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstEveningEventsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstEveningEvents);

        txtEveningEvents.setColumns(20);
        txtEveningEvents.setRows(5);
        jScrollPane2.setViewportView(txtEveningEvents);

        lblStartTime.setText("Időpont");
        lblStartTime.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblStartTime.setAlignmentX(0.5F);

        btnSumOfPrice.setText("Összár");
        btnSumOfPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumOfPriceActionPerformed(evt);
            }
        });

        lblSumOfPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSumOfPrice.setText("Összár");

        lblTicketPrice.setText("Jegyár");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(lblTicketPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnSumOfPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(lblSumOfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSumOfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSumOfPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTicketPrice)
                .addGap(0, 85, Short.MAX_VALUE))
        );

        lblStartTime.getAccessibleContext().setAccessibleName("Label4");
        lblStartTime.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void lstEveningEventsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstEveningEventsValueChanged
        int target = lstEveningEvents.getAnchorSelectionIndex();
        lblStartTime.setText("Időpont: " + eveningEvents.get(target).getDate());
        lblTicketPrice.setText("Jegyár: " + eveningEvents.get(target).getPrice() + " Ft");
    }//GEN-LAST:event_lstEveningEventsValueChanged

    private void btnSumOfPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumOfPriceActionPerformed
        lblSumOfPrice.setText(Control.sumOfPrices() + " Ft");
    }//GEN-LAST:event_btnSumOfPriceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSumOfPrice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblStartTime;
    private javax.swing.JLabel lblSumOfPrice;
    private javax.swing.JLabel lblTicketPrice;
    private javax.swing.JList<String> lstEveningEvents;
    private javax.swing.JTextArea txtEveningEvents;
    // End of variables declaration//GEN-END:variables
}
