package aControl;

import aSurface.HelpFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author KissJGabi
 */
public class MainFrame extends javax.swing.JFrame {

    private final int FRAME_WIDTH = 618;
    private final int FRAME_HEIGHT = 438;
    private final String FRAME_TITLE = "Age Of Pubs";

    private Control c;
    private HelpFrame helpframe = new HelpFrame();

    public MainFrame() {
        initComponents();
        super.setSize(FRAME_WIDTH, FRAME_HEIGHT);
        super.setTitle(FRAME_TITLE);
        super.setLocationRelativeTo(null);
    }

    private void start() {
        enableBookingTab(false);
        enableMenuSort(false);
        this.setVisible(true);
        c = new Control(tavernPanel1, bookingPanel1, this);
        tavernPanel1.setControl(c);
        bookingPanel1.setControl(c);
        c.start();
    }

    public void enableMenuSort(boolean enable) {
        menuBarSort.setEnabled(enable);
        menuOut.setEnabled(enable);
    }

    public void enableBookingTab(boolean enable) {
        jTabbedPane1.setEnabledAt(1, enable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSort = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tavernPanel1 = new aSurface.TavernPanel();
        bookingPanel1 = new aSurface.BookingPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuBarFile = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        menuInputFromDB = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuFromFliChooser = new javax.swing.JMenuItem();
        menuFomFixedFile = new javax.swing.JMenuItem();
        menuOut = new javax.swing.JMenu();
        menuDataOut = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuTxtFilleOut = new javax.swing.JMenuItem();
        menuBinaryFileWrite = new javax.swing.JMenuItem();
        menuBarSort = new javax.swing.JMenu();
        rbtnAbcSorted = new javax.swing.JRadioButtonMenuItem();
        rbtnPriceSorted = new javax.swing.JRadioButtonMenuItem();
        rbtnAlciholSorted = new javax.swing.JRadioButtonMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        chkAscending = new javax.swing.JCheckBoxMenuItem();
        menuBarHelp = new javax.swing.JMenu();
        menuHelp = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabbedPane1MousePressed(evt);
            }
        });
        jTabbedPane1.addTab("csapszék", tavernPanel1);
        jTabbedPane1.addTab("könyvelés", null, bookingPanel1, "");
        jTabbedPane1.setEnabledAt(1, false);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        menuBarFile.setText("Fájl");

        jMenu3.setText("Adatbevitel");

        menuInputFromDB.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        menuInputFromDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aControl/database_icon.jpg"))); // NOI18N
        menuInputFromDB.setText("adatbázisból");
        menuInputFromDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInputFromDBActionPerformed(evt);
            }
        });
        jMenu3.add(menuInputFromDB);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aControl/file_icon.jpg"))); // NOI18N
        jMenu1.setText("fájlból");

        menuFromFliChooser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        menuFromFliChooser.setText("választott helyről");
        menuFromFliChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFromFliChooserActionPerformed(evt);
            }
        });
        jMenu1.add(menuFromFliChooser);

        menuFomFixedFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        menuFomFixedFile.setMnemonic('D');
        menuFomFixedFile.setText("fix helyről");
        menuFomFixedFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFomFixedFileActionPerformed(evt);
            }
        });
        jMenu1.add(menuFomFixedFile);

        jMenu3.add(jMenu1);

        menuBarFile.add(jMenu3);

        menuOut.setText("Adatkiírás");

        menuDataOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        menuDataOut.setText("Adatbázisba");
        menuOut.add(menuDataOut);

        jMenu5.setText("Fájlba");

        menuTxtFilleOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        menuTxtFilleOut.setText("text fájlba");
        menuTxtFilleOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTxtFilleOutActionPerformed(evt);
            }
        });
        jMenu5.add(menuTxtFilleOut);

        menuBinaryFileWrite.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        menuBinaryFileWrite.setText("bináris fájlba");
        menuBinaryFileWrite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBinaryFileWriteActionPerformed(evt);
            }
        });
        jMenu5.add(menuBinaryFileWrite);

        menuOut.add(jMenu5);

        menuBarFile.add(menuOut);

        jMenuBar1.add(menuBarFile);

        menuBarSort.setText("Rendezés");
        btnGroupSort.add(menuBarSort);
        menuBarSort.setEnabled(false);

        btnGroupSort.add(rbtnAbcSorted);
        rbtnAbcSorted.setSelected(true);
        rbtnAbcSorted.setText("névsorba");
        rbtnAbcSorted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAbcSortedActionPerformed(evt);
            }
        });
        menuBarSort.add(rbtnAbcSorted);

        btnGroupSort.add(rbtnPriceSorted);
        rbtnPriceSorted.setText("ár szerint");
        rbtnPriceSorted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPriceSortedActionPerformed(evt);
            }
        });
        menuBarSort.add(rbtnPriceSorted);

        btnGroupSort.add(rbtnAlciholSorted);
        rbtnAlciholSorted.setText("alkoholfok szerint");
        rbtnAlciholSorted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAlciholSortedActionPerformed(evt);
            }
        });
        menuBarSort.add(rbtnAlciholSorted);
        menuBarSort.add(jSeparator1);

        chkAscending.setSelected(true);
        chkAscending.setText("növekvően");
        chkAscending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAscendingActionPerformed(evt);
            }
        });
        menuBarSort.add(chkAscending);

        jMenuBar1.add(menuBarSort);

        menuBarHelp.setText("Súgó");

        menuHelp.setText("Súgó");
        menuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHelpActionPerformed(evt);
            }
        });
        menuBarHelp.add(menuHelp);

        menuAbout.setText("Névjegy");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        menuBarHelp.add(menuAbout);

        jMenuBar1.add(menuBarHelp);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuInputFromDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInputFromDBActionPerformed
        if (c.inputFromDB()) {
            enableBookingTab(true);
            enableMenuSort(true);
            c.showbookingDatas();
        }
    }//GEN-LAST:event_menuInputFromDBActionPerformed

    private void menuFomFixedFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFomFixedFileActionPerformed
        if (c.inputFromFile()) {
            enableBookingTab(true);
            enableMenuSort(true);
            c.showbookingDatas();
        }
    }//GEN-LAST:event_menuFomFixedFileActionPerformed

    private void menuFromFliChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFromFliChooserActionPerformed
        if (c.inputFromSelectedFile()) {
            enableBookingTab(true);
            enableMenuSort(true);
            c.showbookingDatas();
        }
    }//GEN-LAST:event_menuFromFliChooserActionPerformed

    private void menuBinaryFileWriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBinaryFileWriteActionPerformed
        c.writeBinFile();
    }//GEN-LAST:event_menuBinaryFileWriteActionPerformed

    private void menuTxtFilleOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTxtFilleOutActionPerformed
        c.writeTxtFile();
    }//GEN-LAST:event_menuTxtFilleOutActionPerformed

    private void rbtnAbcSortedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAbcSortedActionPerformed
        c.sortByAbc(chkAscending.isSelected());
    }//GEN-LAST:event_rbtnAbcSortedActionPerformed

    private void rbtnPriceSortedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPriceSortedActionPerformed
        c.sortByPrice(chkAscending.isSelected());
    }//GEN-LAST:event_rbtnPriceSortedActionPerformed

    private void rbtnAlciholSortedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAlciholSortedActionPerformed
        c.sortByAlcohol(chkAscending.isSelected());
    }//GEN-LAST:event_rbtnAlciholSortedActionPerformed

    private void chkAscendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAscendingActionPerformed
        if (rbtnAbcSorted.isSelected()) {
            c.sortByAbc(chkAscending.isSelected());
        }
        if (rbtnAbcSorted.isSelected()) {
            c.sortByPrice(chkAscending.isSelected());
        }
        if (rbtnAbcSorted.isSelected()) {
            c.sortByAlcohol(chkAscending.isSelected());
        }
    }//GEN-LAST:event_chkAscendingActionPerformed

    private void jTabbedPane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MousePressed
        c.showbookingDatas();
    }//GEN-LAST:event_jTabbedPane1MousePressed

    private void menuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHelpActionPerformed
        helpframe.setLocationRelativeTo(this);
        helpframe.setVisible(true);
    }//GEN-LAST:event_menuHelpActionPerformed

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        JOptionPane.showMessageDialog(this,
                "Age of Tavern V0.9");
    }//GEN-LAST:event_menuAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().start();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private aSurface.BookingPanel bookingPanel1;
    private javax.swing.ButtonGroup btnGroupSort;
    private javax.swing.JCheckBoxMenuItem chkAscending;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenu menuBarFile;
    private javax.swing.JMenu menuBarHelp;
    private javax.swing.JMenu menuBarSort;
    private javax.swing.JMenuItem menuBinaryFileWrite;
    private javax.swing.JMenuItem menuDataOut;
    private javax.swing.JMenuItem menuFomFixedFile;
    private javax.swing.JMenuItem menuFromFliChooser;
    private javax.swing.JMenuItem menuHelp;
    private javax.swing.JMenuItem menuInputFromDB;
    private javax.swing.JMenu menuOut;
    private javax.swing.JMenuItem menuTxtFilleOut;
    private javax.swing.JRadioButtonMenuItem rbtnAbcSorted;
    private javax.swing.JRadioButtonMenuItem rbtnAlciholSorted;
    private javax.swing.JRadioButtonMenuItem rbtnPriceSorted;
    private aSurface.TavernPanel tavernPanel1;
    // End of variables declaration//GEN-END:variables
}
