/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aSurface;

import static aBasis.Global.*;
import aControl.Control;
import java.awt.Dimension;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author b6dmin
 */
public class ControlPanel extends javax.swing.JPanel {

    private Control c;

    public void setControl(Control c) {
        this.c = c;
    }

    public void setup() {
        System.out.println("controlPanel: "
                + this.getWidth() + "x" + this.getHeight());
        setButtonActivity(false);
    }

    public int controlWidth() {
        return this.getWidth();
    }

    public int controlHeight() {
        return this.getHeight();
    }

    private final DefaultListModel<String> userListModel;

    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {
        System.out.println("controlPanel()");
        this.userListModel = new DefaultListModel<>();
        initComponents();
        super.setPreferredSize(new Dimension(CONTROL_WIDTH, CONTROL_HEIGHT));
        lblTitle.setText(CONTROL_LBL_TITLE);
        lblRegistered.setText(CONTROL_LBL_REISTERED);
        btnBroadCast.setText(CONTROL_BTN_BROADCAST);
        btnUnique.setText(CONTROL_BTN_UNIQUE);
        lstUser.setModel(userListModel);
    }

    public void setButtonBroadcast(boolean b) {
        btnBroadCast.setEnabled(b);
    }

    public void setButtonUnique(boolean b) {
        btnUnique.setEnabled(b);
    }

    public void setListUser(boolean b) {
        lstUser.setEnabled(b);
    }

    public void setButtonActivity(boolean b) {
        setButtonBroadcast(b);
        setButtonUnique(b);
        setListUser(b);
    }

    public void setTitleInvisible() {
        lblTitle.setBounds(0, 0, 0, 0);
    }

    public void fillUserList(List<String> list) {
        userListModel.clear();
        lstUser.clearSelection();
        list.forEach(userListModel::addElement);
    }

    public void clearTitleText() {
        System.out.println("controlPanel.clearTitleText()");
        lblTitle.setText(" ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblRegistered = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstUser = new javax.swing.JList<>();
        btnUnique = new javax.swing.JButton();
        btnBroadCast = new javax.swing.JButton();

        setBackground(new java.awt.Color(237, 237, 245));

        lblTitle.setBackground(new java.awt.Color(59, 89, 153));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("jLabel1");
        lblTitle.setOpaque(true);

        lblRegistered.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRegistered.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistered.setText("jLabel1");

        lstUser.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstUser.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lstUserMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(lstUser);

        btnUnique.setText("jButton1");
        btnUnique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUniqueActionPerformed(evt);
            }
        });

        btnBroadCast.setText("jButton1");
        btnBroadCast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBroadCastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRegistered, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUnique, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(btnBroadCast, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRegistered)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnBroadCast)
                .addGap(18, 18, 18)
                .addComponent(btnUnique)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBroadCastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBroadCastActionPerformed
        c.broadcastMainProcess();
    }//GEN-LAST:event_btnBroadCastActionPerformed

    private void btnUniqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUniqueActionPerformed
        c.uniqueMainProcess();
    }//GEN-LAST:event_btnUniqueActionPerformed

    private void lstUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstUserMousePressed
        c.startMainProcess(lstUser.getSelectedValue());
    }//GEN-LAST:event_lstUserMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBroadCast;
    private javax.swing.JButton btnUnique;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRegistered;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<String> lstUser;
    // End of variables declaration//GEN-END:variables
}
