/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aSurface;

import static aBasis.Global.*;
import aControl.Control;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.KeyEvent;

/**
 *
 * @author b6dmin
 */
public class GraphityPanel extends javax.swing.JPanel {

    private Control c;

    public void setControl(Control c) {
        this.c = c;
    }

    public int getGraphityHeight() {
        return this.getHeight();
    }

    public int getGraphityWidth() {
        return this.getWidth();
    }

    public void setup() {
        System.out.println("graphityPanel: "
                + this.getWidth() + "x" + this.getHeight());
    }

    public int graphityWidth() {
        return this.getWidth();
    }

    public int graphityHeight() {
        return this.getHeight();
    }

    /**
     * Creates new form GraphityPanel
     */
    public GraphityPanel() {
        System.out.println("MiddlePanel()");
        initComponents();
        super.setPreferredSize(new Dimension(GRAPHITY_WIDTH, GRAPHITY_HEIGHT));
        btnSearch.setText(GRAPHITY_BTN_SEARCH);
    }

    public void clearSearchTextField() {
        txtSearch.setText("");
    }

    public void setSearchVisible() {
        btnSearch.setBounds(SEARCH_BTN_X, SEARCH_BTN_Y,
                SEARCH_BTN_WIDTH, SEARCH_BTN_HEIGHT);
        txtSearch.setBounds(SEARCH_TXT_X, SEARCH_TXT_Y,
                SEARCH_TXT_WIDTH, SEARCH_TXT_HEIGHT);
    }

    public void setSearchInvisible() {
        btnSearch.setBounds(0, 0, 0, 0);
        txtSearch.setBounds(0, 0, 0, 0);
    }

    private void startControlMainProcess(String s) {
        if (!s.isEmpty()) {
            c.clearSelected();
            c.startMainProcess(s);
        }
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        switch (state) {
            case PROLOG: {
                g.drawImage(GRAPHITY_PROLOG, 0, 0,
                        this.getWidth(), this.getHeight(), this);
                g.drawImage(LOGO, LOGO_X, LOGO_Y,
                        this.getWidth(), LOGO_HEIGHT, this);
                g.drawImage(DECOR, DECOR_X, DECOR_Y,
                        DECOR_WIDTH, DECOR_HEIGHT, this);
                String str = GRAPHITY_PROLOG_TXT;
                g.setColor(Color.WHITE);
                g.setFont(new Font("Serif", Font.BOLD, 31));
                int width = g.getFontMetrics().stringWidth(str);
                int height = g.getFontMetrics().getHeight();
                g.drawString(str,
                        (GRAPHITY_WIDTH - width) / 2, 3 * height / 4);
                break;
            }
            case EPILOG:
            case EXIT: {
                g.drawImage(GRAPHITY_FINALE, 0, 0,
                        this.getWidth(), this.getHeight(), this);
                String str = PROCESS_STATE.EPILOG.toString();
                g.setColor(Color.BLUE);
                g.setFont(new Font("Serif", Font.BOLD, 31));
                int width = g.getFontMetrics().stringWidth(str);
                int height = g.getFontMetrics().getHeight();
                g.drawString(str, (GRAPHITY_WIDTH - width) / 2, 3 * height / 4);
                break;
            }
            default: {
                g.drawImage(GRAPHITY_MAIN, 0, 0,
                        this.getWidth(), this.getHeight(), this);
                g.drawImage(LOGO, LOGO_X, LOGO_Y,
                        this.getWidth(), LOGO_HEIGHT, this);
                String str = GRAPHITY_LOGOUT_TXT;
                g.setColor(Color.WHITE);
                g.setFont(new Font("Serif", Font.PLAIN, 18));
                int width = g.getFontMetrics().stringWidth(str);
                int height = g.getFontMetrics().getHeight();
                g.drawString(str,
                        GRAPHITY_WIDTH - width, height);
            }
        }
        if (c != null) {
            c.drawGraphity(g);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        setLayout(null);

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSearch.setToolTipText("");
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });
        add(txtSearch);
        txtSearch.setBounds(0, 0, 0, 0);

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSearch.setText("jButton1");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch);
        btnSearch.setBounds(0, 0, 0, 0);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        startControlMainProcess(txtSearch.getText());
    }//GEN-LAST:event_btnSearchActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        c.clickOnGraphity(evt.getX(), evt.getY(), evt.getButton());
    }//GEN-LAST:event_formMousePressed

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            startControlMainProcess(txtSearch.getText());
        }
    }//GEN-LAST:event_txtSearchKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
