package aSurface;

import aBasis.Drink;
import aBasis.SortableListModel;
import aControl.Control;
import java.text.NumberFormat;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author b6dmin
 */
public class TavernPanel extends javax.swing.JPanel {

    private SortableListModel<Drink> drinkListModel
            = new SortableListModel<Drink>();

    private Control control;
    private Locale locale = this.getLocale();

    public void setControl(Control c) {
        this.control = c;
        lstDrink.setModel(drinkListModel);
    }

    /**
     * Creates new form MainFrame
     */
    public TavernPanel() {
        initComponents();
        lstDrink.setModel(drinkListModel);
        clearClickedDrink();
    }

    public void listDrink(List<Drink> list) {
        drinkListModel.clear();
        list.forEach((drink) -> {
            drinkListModel.addElement(drink);
        });
    }

    private void ascending() {
        clearClickedDrink();
        Drink.setChoosedCriterion(Drink.Criterion.NAME, Drink.ASCENDING);
        drinkListModel.sort();
    }

    private void descending() {
        clearClickedDrink();
        Drink.setChoosedCriterion(Drink.Criterion.NAME, Drink.DESCENDING);
        drinkListModel.sort();
    }

    private void clearClickedDrink() {
        lstDrink.clearSelection();
        lblInfo.setText("Info");
    }

    private void showClickedDrink() {
        Drink clickedDrink = lstDrink.getSelectedValue();
        if (clickedDrink != null) {
            NumberFormat numformat = NumberFormat.getInstance(locale);
            NumberFormat payformat = NumberFormat.getCurrencyInstance(locale);
            lblInfo.setText(numformat.format(clickedDrink.getUNIT()) + " dl "
                    + payformat.format(clickedDrink.unitPrice()));
        }
    }

    public void setLocaleDatas(Locale locale) {
        this.locale = locale;
        if (radDescending.isSelected()) {
            descending();
        }
        if (radAscending.isSelected()) {
            ascending();
        }
        showClickedDrink();
    }

    public void setTextLocale(ResourceBundle bundle) {
        lblHeader.setText(bundle.getString("DRINK_LIST"));
        radAscending.setText(bundle.getString("ASCENDING"));
        radDescending.setText(bundle.getString("DESCENDING"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSort = new javax.swing.ButtonGroup();
        lblHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDrink = new javax.swing.JList<>();
        lblInfo = new javax.swing.JLabel();
        radAscending = new javax.swing.JRadioButton();
        radDescending = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 204));

        lblHeader.setBackground(new java.awt.Color(255, 255, 204));
        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Itallap");

        lstDrink.setModel(new javax.swing.AbstractListModel<Drink>() {
            Drink[] d;
            public int getSize() { return d.length; }
            public Drink getElementAt(int i) { return d[i]; }
        });
        lstDrink.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstDrink.setVisibleRowCount(12);
        lstDrink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lstDrinkMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(lstDrink);

        lblInfo.setText(" Info");

        radAscending.setBackground(new java.awt.Color(255, 255, 204));
        btnSort.add(radAscending);
        radAscending.setText("Növekvően");
        radAscending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAscendingActionPerformed(evt);
            }
        });

        radDescending.setBackground(new java.awt.Color(255, 255, 204));
        btnSort.add(radDescending);
        radDescending.setText("Csökkenően");
        radDescending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radDescendingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(radAscending, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radDescending, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblInfo)
                .addGap(18, 18, 18)
                .addComponent(radAscending)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radDescending)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radAscendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAscendingActionPerformed
        ascending();
    }//GEN-LAST:event_radAscendingActionPerformed

    private void radDescendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radDescendingActionPerformed
        descending();
    }//GEN-LAST:event_radDescendingActionPerformed

    private void lstDrinkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstDrinkMousePressed
        showClickedDrink();
    }//GEN-LAST:event_lstDrinkMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnSort;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JList<Drink> lstDrink;
    private javax.swing.JRadioButton radAscending;
    private javax.swing.JRadioButton radDescending;
    // End of variables declaration//GEN-END:variables
}
