/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aSurface;

import static aBasis.Global.*;
import aControl.Control;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;

/**
 *
 * @author b6dmin
 */
public class MiddlePanel extends javax.swing.JPanel {

    private Control c;

    public void setControl(Control c) {
        this.c = c;
    }

    Graphics g;

    public void setup() {
        System.out.println("middlePanel: "
                + this.getWidth() + "x" + this.getHeight());

        txtArea.setForeground(Color.WHITE);
        txtArea.setText(TOTAL_TEXT);

        TEXT_WIDTH = (int) txtArea.getPreferredSize().getWidth() + 8;
        TEXT_HEIGHT = (int) txtArea.getPreferredSize().getHeight() + 8;

        TEXT_MARGIN_H = (GRAPHITY_WIDTH - TEXT_WIDTH) / 2;
        TEXT_MARGIN_V = (GRAPHITY_HEIGHT - TEXT_HEIGHT) / 2;

        txtArea.setSize(TEXT_WIDTH, TEXT_HEIGHT);
        scrollPanel.setSize(TEXT_WIDTH, TEXT_HEIGHT);

        scrollPanel.setLocation(TEXT_MARGIN_H, TEXT_MARGIN_V);

        this.revalidate();
        System.out.println(">" + TOTAL_TEXT);
        System.out.println(TEXT_WIDTH + " : " + TEXT_HEIGHT);

        this.revalidate();
    }

    /**
     * Creates new form MiddlePanel
     */
    public MiddlePanel() {
        System.out.println("MiddlePanel()");
        initComponents();
        super.setPreferredSize(new Dimension(GRAPHITY_WIDTH, GRAPHITY_HEIGHT));
    }

    public void removeTxtPanel() {
        if (scrollPanel.isValid()) {
            remove(this.scrollPanel);
        }
    }

    public void showText(String actualText) {
        txtArea.setForeground(Color.BLUE);
        txtArea.setText(actualText);

    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        switch (state) {
            case PROLOG: {
                g.drawImage(GRAPHITY_PROLOG, 0, 0,
                        this.getWidth(), this.getHeight(), this);
                String str = PROCESS_STATE.PROLOG.toString();
                g.setColor(Color.WHITE);
                g.setFont(new Font("Serif", Font.BOLD, 31));
                int width = g.getFontMetrics().stringWidth(str);
                g.drawString(str,
                        (GRAPHITY_WIDTH - width) / 2,
                        TEXT_MARGIN_V / 2);
                break;
            }
            case EXIT: {
                g.drawImage(GRAPHITY_FINALE, 0, 0,
                        this.getWidth(), this.getHeight(), this);
                String str = PROCESS_STATE.EPILOG.toString();
                g.setColor(Color.WHITE);
                g.setFont(new Font("Serif", Font.BOLD, 31));
                int width = g.getFontMetrics().stringWidth(str);
                g.drawString(str,
                        (GRAPHITY_WIDTH - width) / 2,
                        GRAPHITY_HEIGHT / 6);
                break;
            }
            default: {
                g.drawImage(GRAPHITY_MAIN, 0, 0,
                        this.getWidth(), this.getHeight(), this);
            }
        }
        if (c != null) {
            c.drawGraphity(g);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanel = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(204, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        setLayout(null);

        scrollPanel.setToolTipText("");

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        txtArea.setRows(5);
        scrollPanel.setViewportView(txtArea);

        add(scrollPanel);
        scrollPanel.setBounds(130, 140, 270, 230);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        c.clickOnGraphity(evt.getX(), evt.getY(), evt.getButton());
    }//GEN-LAST:event_formMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
