/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aSurface;

import aControl.Control;
import java.awt.Graphics;
import java.util.TimeZone;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author b6dmin
 */
public class ClockPanel extends javax.swing.JPanel {

    private Control control;

    DefaultComboBoxModel timeZoneModel = new DefaultComboBoxModel();

    public void setControl(Control control) {
        this.control = control;
    }

    public void fillComboTimeZones(TimeZone[] timeZoneList) {
        int dummy = control.getActualTimeZone();
        for (TimeZone t : timeZoneList) {
            comboTimeZones.addItem(t.getID());
        }
        comboTimeZones.setSelectedIndex(dummy);
    }

    /**
     * Creates new form ClockPanel
     */
    public ClockPanel() {
        initComponents();
        comboTimeZones.setModel(timeZoneModel);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        //System.out.println("cPanel paintComponent");
        if (control != null) {
            control.drawOnClockPanel(g);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboTimeZones = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(540, 360));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        setLayout(null);

        comboTimeZones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboTimeZones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTimeZonesActionPerformed(evt);
            }
        });
        add(comboTimeZones);
        comboTimeZones.setBounds(0, 0, 540, 20);

        jLabel1.setText("2019.07.16@ClickMeBaby!");
        add(jLabel1);
        jLabel1.setBounds(390, 340, 150, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void comboTimeZonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTimeZonesActionPerformed
        control.changeTimeZone(comboTimeZones.getSelectedIndex());
    }//GEN-LAST:event_comboTimeZonesActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        control.directionChange();
    }//GEN-LAST:event_formMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboTimeZones;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
