CREATE TABLE CIKKEK ( id int not null primary key, szerzo varchar(40), cim varchar(50), karakterszam int, hazugsagszazalek int)
INSERT INTO CIKKEK VALUES(1,'Fecsegő Ferdinánd','Hulla a bokorban',220,30)
INSERT INTO CIKKEK VALUES(2,'Csacsogó Csilla','Csacsogás',1000,40)
INSERT INTO CIKKEK VALUES(3,'Igazmondó Pál','Őszinte politika',300,80)
INSERT INTO CIKKEK VALUES(4,'Rossztollú Rezső','Mellébeszélés',250,60)
