package aSurface;

import aBasis.Guard;
import aBasis.Participant;
import aBasis.Prisoner;
import aControl.Control;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author KissJGabi
 */
public class SimulationPanel extends javax.swing.JPanel {

    private DefaultListModel<Participant> guardListModel
            = new DefaultListModel<>();
    private DefaultListModel<Participant> prisonerListModel
            = new DefaultListModel<>();
    private DefaultListModel<Participant> evilListModel
            = new DefaultListModel<>();
    private DefaultListModel<String> diaryListModel
            = new DefaultListModel<>();

    private Control control;

    /**
     * Creates new form SimulationPanel
     */
    public SimulationPanel() {
        initComponents();
        lstGuard.setModel(guardListModel);
        lstPrisoner.setModel(prisonerListModel);
        lstEvil.setModel(evilListModel);
        lstDiary.setModel(diaryListModel);
    }

    public void setControl(Control c) {
        this.control = c;
    }

    private void clearPanel() {
        guardListModel.clear();
        prisonerListModel.clear();
        evilListModel.clear();
        diaryListModel.clear();
        lblAgression.setText("");
        lblApathy.setText("");
        lblExperiencesDays.setText("");
    }

    public void guardList(List<Guard> list) {
        list.forEach((guard) -> {
            guardListModel.addElement(guard);
        });
    }

    public void prisonerList(List<Prisoner> list) {
        list.forEach((prisoner) -> {
            prisonerListModel.addElement(prisoner);
        });
    }

    public void evilList(List<Guard> list) {
        list.forEach((guard) -> {
            evilListModel.addElement(guard);
        });
    }

    public void diaryList(List<String> list) {
        list.forEach((diary) -> {
            diaryListModel.addElement(diary);
        });
    }

    public void agressionLabel(int a) {
        lblAgression.setText("Az agressziószint: " + a);
    }

    public void apathyLabel(int a) {
        lblApathy.setText("Fásultságszint: " + a);
    }

    public void daysLabel(int d) {
        lblExperiencesDays.setText("A kísérlet " + d + ". napja");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAgression = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstGuard = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPrisoner = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstDiary = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstEvil = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSortPrisoners = new javax.swing.JButton();
        lblApathy = new javax.swing.JLabel();
        btnNewDay = new javax.swing.JButton();
        btnRestart = new javax.swing.JButton();
        lblExperiencesDays = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 153));

        lblAgression.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAgression.setText("Agressziószint:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Rabok");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Napló");

        jScrollPane1.setMinimumSize(new java.awt.Dimension(200, 23));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 194));

        lstGuard.setModel(new javax.swing.AbstractListModel<Participant>() {
            Participant[] p;
            public int getSize() { return p.length; }
            public Participant getElementAt(int i) { return p[i]; }
        });
        lstGuard.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstGuard.setVisibleRowCount(12);
        lstGuard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstGuardMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstGuard);

        jScrollPane2.setMinimumSize(new java.awt.Dimension(200, 23));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(200, 194));

        lstPrisoner.setModel(new javax.swing.AbstractListModel<Participant>() {
            Participant[] p;
            public int getSize() { return p.length; }
            public Participant getElementAt(int i) { return p[i]; }
        });
        lstPrisoner.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstPrisoner.setVisibleRowCount(12);
        lstPrisoner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstPrisonerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstPrisoner);

        jScrollPane3.setMinimumSize(new java.awt.Dimension(200, 23));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(200, 291));

        lstDiary.setModel(new javax.swing.AbstractListModel<String>() {
            String[] s;
            public int getSize() { return s.length; }
            public String getElementAt(int i) { return s[i]; }
        });
        lstDiary.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstDiary.setVisibleRowCount(18);
        jScrollPane3.setViewportView(lstDiary);

        jScrollPane4.setMinimumSize(new java.awt.Dimension(200, 23));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(200, 97));

        lstEvil.setModel(new javax.swing.AbstractListModel<Participant>() {
            Participant[] p;
            public int getSize() { return p.length; }
            public Participant getElementAt(int i) { return p[i]; }
        });
        lstEvil.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstEvil.setVisibleRowCount(6);
        jScrollPane4.setViewportView(lstEvil);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Börtönőrök");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Leggonoszabb őrök");

        btnSortPrisoners.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSortPrisoners.setText("Rendezve");
        btnSortPrisoners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortPrisonersActionPerformed(evt);
            }
        });

        lblApathy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblApathy.setText("Fásultságszint");

        btnNewDay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNewDay.setText("ÚJ NAP");
        btnNewDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewDayActionPerformed(evt);
            }
        });

        btnRestart.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRestart.setText("RESTART");
        btnRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestartActionPerformed(evt);
            }
        });

        lblExperiencesDays.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblExperiencesDays.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExperiencesDays.setText("A kísérlet 0. napja");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblAgression, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSortPrisoners, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblApathy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRestart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNewDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblExperiencesDays, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAgression)
                                    .addComponent(lblApathy)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSortPrisoners, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRestart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblExperiencesDays)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lstGuardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstGuardMouseClicked
        diaryListModel.clear();
        lstPrisoner.clearSelection();
        control.showGuardDiarys(lstGuard.getSelectedValue());
    }//GEN-LAST:event_lstGuardMouseClicked

    private void lstPrisonerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstPrisonerMouseClicked
        diaryListModel.clear();
        lstGuard.clearSelection();
        control.showPrisonerDiarys(lstPrisoner.getSelectedValue());
    }//GEN-LAST:event_lstPrisonerMouseClicked

    private void btnSortPrisonersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortPrisonersActionPerformed
        diaryListModel.clear();
        prisonerListModel.clear();
        control.sortPrisoners();
    }//GEN-LAST:event_btnSortPrisonersActionPerformed

    private void btnRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestartActionPerformed
        clearPanel();
        control.restart();
    }//GEN-LAST:event_btnRestartActionPerformed

    private void btnNewDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewDayActionPerformed
        lstPrisoner.clearSelection();
        lstGuard.clearSelection();
        diaryListModel.clear();
        prisonerListModel.clear();
        evilListModel.clear();
        control.newDay();
    }//GEN-LAST:event_btnNewDayActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewDay;
    private javax.swing.JButton btnRestart;
    private javax.swing.JButton btnSortPrisoners;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAgression;
    private javax.swing.JLabel lblApathy;
    private javax.swing.JLabel lblExperiencesDays;
    private javax.swing.JList<String> lstDiary;
    private javax.swing.JList<Participant> lstEvil;
    private javax.swing.JList<Participant> lstGuard;
    private javax.swing.JList<Participant> lstPrisoner;
    // End of variables declaration//GEN-END:variables
}
