/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aSurface;

import aControl.Control;
import static aGlobal.Global.*;
import java.awt.Dimension;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author b6dmin
 */
public class ControlPanel extends javax.swing.JPanel {

    /**
     * Creates new form ControlPanel
     */
    private Control c;

    public void setControl(Control c) {
        this.c = c;
    }

    public void setup() {
        System.out.println("controlPanel: "
                + this.getWidth() + "x" + this.getHeight());
        setButtonActivity(false);
    }

    public int controlWidth() {
        return this.getWidth();
    }

    public int controlHeight() {
        return this.getHeight();
    }

    private final DefaultListModel<String> listModel;
    private final DefaultListModel<String> targetModel;

    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {
        System.out.println("controlPanel()");
        this.listModel = new DefaultListModel<>();
        this.targetModel = new DefaultListModel<>();
        initComponents();
        super.setPreferredSize(new Dimension(CONTROL_WIDTH, CONTROL_HEIGHT));
        lblTitle.setText(CONTROL_LBL_TITLE);
        lblList.setText(CONTROL_LBL_STUDENTS);
        lblTarget.setText(CONTROL_LBL_EMPLOYEES);
        btnStart.setText(CONTROL_BTN_BYE);
        lstList.setModel(listModel);
        lstTarget.setModel(targetModel);
    }

    public void setButtonstart(boolean b) {
        btnStart.setEnabled(b);
    }

    public void setLists(boolean b) {
        lstList.setEnabled(b);
        lstTarget.setEnabled(b);
    }

    public void setButtonActivity(boolean b) {
        setButtonstart(b);
        setLists(b);
    }

    public void setTitleInvisible() {
        lblTitle.setBounds(0, 0, 0, 0);
    }

    public void fillList(List<String> list) {
        listModel.clear();
        list.forEach(listModel::addElement);
    }

    public void removeFromList(String str) {
        listModel.removeElement(str);
    }

    public void addToTarget(String str) {
        targetModel.addElement(str);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstTarget = new javax.swing.JList<>();
        lblTarget = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 153));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("jLabel1");

        lblList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblList.setText("jLabel2");
        lblList.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lstList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstList);

        lstTarget.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstTarget);

        lblTarget.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTarget.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTarget.setText("jLabel1");
        lblTarget.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btnStart.setText("jButton1");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addComponent(lblTarget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTarget)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStart)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        c.finishFinale();
    }//GEN-LAST:event_btnStartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblList;
    private javax.swing.JLabel lblTarget;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<String> lstList;
    private javax.swing.JList<String> lstTarget;
    // End of variables declaration//GEN-END:variables
}
