/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aSurface;

import aControl.Control;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.event.MouseEvent;
import javax.swing.JComponent;
import javax.swing.ToolTipManager;

/**
 *
 * @author b6dmin
 */
public class ClockPanel extends javax.swing.JPanel {

    private Control control;

    private final String STARTLABEL = "Start";
    private final String STOP_LABEL = "Stop";

    ToolTipManager manager;

    public void setControl(Control control) {
        this.control = control;
    }

    /**
     * Creates new form ClockPanel
     */
    public ClockPanel() {
        initComponents();
        btnStartStop.setText(STARTLABEL);
        sliderTimeUnit.setToolTipText("" + sliderTimeUnit.getValue());
        manager = ToolTipManager.sharedInstance();
        manager.setInitialDelay(0);
    }

    public void showToolTipNow(JComponent component) {
        Point p = component.getMousePosition();
        int x = p.x;
        int y = p.y;
        manager.mouseMoved(new MouseEvent(component, MouseEvent.MOUSE_MOVED,
                System.currentTimeMillis(), 0, x, y, 0, false));
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (control != null) {
            control.drawOnClockPanel(g);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStartStop = new javax.swing.JButton();
        sliderTimeUnit = new javax.swing.JSlider();

        setLayout(null);

        btnStartStop.setText("jButton1");
        btnStartStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartStopActionPerformed(evt);
            }
        });
        add(btnStartStop);
        btnStartStop.setBounds(10, 11, 73, 23);

        sliderTimeUnit.setMajorTickSpacing(1000);
        sliderTimeUnit.setMaximum(10000);
        sliderTimeUnit.setMinimum(100);
        sliderTimeUnit.setMinorTickSpacing(100);
        sliderTimeUnit.setSnapToTicks(true);
        sliderTimeUnit.setValue(1000);
        sliderTimeUnit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sliderTimeUnit.setOpaque(false);
        sliderTimeUnit.setRequestFocusEnabled(false);
        sliderTimeUnit.setVerifyInputWhenFocusTarget(false);
        sliderTimeUnit.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderTimeUnitStateChanged(evt);
            }
        });
        add(sliderTimeUnit);
        sliderTimeUnit.setBounds(10, 480, 480, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartStopActionPerformed
        control.changeState();
        if (btnStartStop.getText().equals(STARTLABEL)) {
            btnStartStop.setText(STOP_LABEL);
        } else {
            btnStartStop.setText(STARTLABEL);
        }
    }//GEN-LAST:event_btnStartStopActionPerformed

    private void sliderTimeUnitStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderTimeUnitStateChanged
        control.changeTimeUnit(sliderTimeUnit.getValue());
        sliderTimeUnit.setToolTipText("" + sliderTimeUnit.getValue());
        showToolTipNow(sliderTimeUnit);

    }//GEN-LAST:event_sliderTimeUnitStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStartStop;
    private javax.swing.JSlider sliderTimeUnit;
    // End of variables declaration//GEN-END:variables
}
