package aControl;

import aBasis.Drink;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author b6dmin
 */
public class MainFrame extends javax.swing.JFrame {

    private final int FRAME_WIDTH = 416;
    private final int FRAME_HEIGHT = 465;
    private final String BUNDLE = "aLocale/Bundle";
    private ResourceBundle bundle;
    private Locale locale;

    private Control c;

    public MainFrame() {
        initComponents();
        bundle = ResourceBundle.getBundle(BUNDLE);
        super.setSize(FRAME_WIDTH, FRAME_HEIGHT);
        super.setTitle(bundle.getString("FRAME_TITLE"));
        super.setLocationRelativeTo(null);
    }

    private void start() {
        this.setVisible(true);
        c = new Control(tavernPanel1, this);
        tavernPanel1.setControl(c);
        c.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tavernPanel1 = new aSurface.TavernPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuHU = new javax.swing.JMenu();
        menuGB = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(tavernPanel1, java.awt.BorderLayout.CENTER);

        menuHU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aControl/Hungary.png"))); // NOI18N
        menuHU.setText("magyar");
        menuHU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuHUMousePressed(evt);
            }
        });
        jMenuBar1.add(menuHU);

        menuGB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aControl/Great-britain.png"))); // NOI18N
        menuGB.setText("english");
        menuGB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuGBMousePressed(evt);
            }
        });
        jMenuBar1.add(menuGB);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuGBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuGBMousePressed
        locale = new Locale("en", "GB");
        useLanguage();
    }//GEN-LAST:event_menuGBMousePressed

    private void menuHUMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHUMousePressed
        locale = new Locale("hu", "HU");
        useLanguage();
    }//GEN-LAST:event_menuHUMousePressed

    private void useLanguage() {
        bundle = ResourceBundle.getBundle(BUNDLE, locale);
        this.setTitle(bundle.getString("FRAME_TITLE"));
        c.setLocaleBundle(locale, bundle);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().start();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuGB;
    private javax.swing.JMenu menuHU;
    private aSurface.TavernPanel tavernPanel1;
    // End of variables declaration//GEN-END:variables
}
