/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aSurface;

import static aBasis.Global.*;
import aControl.Control;

/**
 *
 * @author b6dmin
 */
public class ResultsPanel extends javax.swing.JPanel {

    private Control c;

    public void setControl(Control c) {
        this.c = c;
        gamePanel1.setControl(c);
    }

    public GamePanel getGamePanel() {
        return gamePanel1;
    }

    /**
     * Creates new form ResultsPanel
     */
    public ResultsPanel() {
        initComponents();
    }

    public void setTextLocale() {
        writeScore(c.getPlayerScore());
        writeTime(c.getRemainingTime());
    }

    public void writeScore(int score) {
        lblScore.setText(rBundle.getString(("LBL_SCORE_TXT")) + score);
    }

    public void writeTime(long time) {
        lblTime.setText(rBundle.getString(("LBL_REMAININGTIME_TXT")) + time);
    }

    public void finishGame() {
        lblScore.setText("");
        lblTime.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gamePanel1 = new aSurface.GamePanel();
        lblScore = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(null);

        javax.swing.GroupLayout gamePanel1Layout = new javax.swing.GroupLayout(gamePanel1);
        gamePanel1.setLayout(gamePanel1Layout);
        gamePanel1Layout.setHorizontalGroup(
            gamePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        gamePanel1Layout.setVerticalGroup(
            gamePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        add(gamePanel1);
        gamePanel1.setBounds(0, 50, 800, 550);

        lblScore.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScore.setText("Pontszám: ");
        add(lblScore);
        lblScore.setBounds(0, 16, 400, 17);

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime.setText("Idő: ");
        add(lblTime);
        lblTime.setBounds(400, 16, 400, 17);

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private aSurface.GamePanel gamePanel1;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblTime;
    // End of variables declaration//GEN-END:variables
}
