package aSurface;

import aBasis.Book;
import aControl.Control;
import java.awt.Dimension;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author b6dmin
 */
public class BookStore extends javax.swing.JPanel {

    private String[] buttonText
            = {"Adatbevitel", "Eredményt mutat", "Eredményt elrejt"};
    private int click;
    private Image myImage
            = new ImageIcon(this.getClass().
                    getResource("/aSurface/tv_vs_konyv.jpg")).getImage();
    private Control c;

    /**
     * Creates new form BookStore
     */
    public BookStore() {
        initComponents();
        btnWithMoreFunction.setText(buttonText[0]);
        setVisibility(false);
    }

    private void setVisibility(boolean visibility) {
        lblTitle.setVisible(visibility);
        lstBookList.setVisible(visibility);
    }

    public void setControl(Control c) {
        this.c = c;
    }

    public void listAllBooks(ArrayList<Book> bookList) {
        JRadioButton rdButton;
        JLabel label;

        int distance_h = 10, distance_v = 20;
        int gap = 40;
        int rdButtonWidth = 300;
        int rdButtonHeight = 20;

        int labelDistance_h = 350;
        int labelWidth = 100;
        int labelHeight = 20;

        int scrollBarWidth = 21;

        for (int ii = 0; ii < bookList.size(); ii++) {
            rdButton = new JRadioButton(bookList.get(ii).toString());
            rdButton.setLocation(distance_h, distance_v + ii * gap);
            rdButton.setSize(rdButtonWidth, rdButtonHeight);
            rdButton.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    int index = (((JRadioButton) e.getSource()).getY()
                            - distance_v) / gap;
                    c.addVote(index);
                }
            });
            this.pnlBackground.add(rdButton);
            buttonGroup1.add(rdButton);

            label = new JLabel(bookList.get(ii).votesText());
            label.setLocation(labelDistance_h, distance_v + ii * gap);
            label.setSize(labelWidth, labelHeight);
            this.pnlBackground.add(label);
        }
        Dimension preferredSize
                = new Dimension(lstBookList.getWidth() - scrollBarWidth,
                        bookList.size() * gap + distance_v);
        pnlBackground.setPreferredSize(preferredSize);
        validate();
    }

    private void setVoteVisibility(boolean visible) {
        buttonGroup1.clearSelection();
        for (Component component : pnlBackground.getComponents()) {
            if (component instanceof JLabel) {
                component.setVisible(visible);
            }
        }
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(myImage, 0, 0, this.getWidth(), this.getHeight(), null);
    }

    public void refresh(int index, String votesText) {
        int labelIndex = 2 * index + 1;
        if (pnlBackground.getComponents()[labelIndex] instanceof JLabel) {
            ((JLabel) pnlBackground.getComponents()[labelIndex]).
                    setText(votesText);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        btnWithMoreFunction = new javax.swing.JButton();
        lstBookList = new javax.swing.JScrollPane();
        pnlBackground = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 153, 153));
        setPreferredSize(new java.awt.Dimension(600, 500));

        lblTitle.setBackground(new java.awt.Color(255, 102, 102));
        lblTitle.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(204, 0, 102));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Könyvkínálat");

        btnWithMoreFunction.setText("jButton1");
        btnWithMoreFunction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithMoreFunctionActionPerformed(evt);
            }
        });

        lstBookList.setBackground(new java.awt.Color(255, 204, 204));
        lstBookList.setForeground(new java.awt.Color(153, 0, 0));
        lstBookList.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lstBookList.setPreferredSize(new java.awt.Dimension(490, 316));

        pnlBackground.setBackground(new java.awt.Color(255, 204, 204));
        pnlBackground.setPreferredSize(new java.awt.Dimension(480, 308));

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );

        lstBookList.setViewportView(pnlBackground);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(btnWithMoreFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lstBookList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lstBookList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnWithMoreFunction)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnWithMoreFunctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithMoreFunctionActionPerformed
        click++;
        if (click == 1) {
            setVisibility(true);
            myImage = null;
            c.openDataBase();
            this.repaint();
        }
        if (click % 2 != 0) {
            btnWithMoreFunction.setText(buttonText[1]);
            setVoteVisibility(false);
        } else {
            btnWithMoreFunction.setText(buttonText[2]);
            setVoteVisibility(true);
        }
    }//GEN-LAST:event_btnWithMoreFunctionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnWithMoreFunction;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane lstBookList;
    private javax.swing.JPanel pnlBackground;
    // End of variables declaration//GEN-END:variables
}
