/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aSurface;

import static aBasis.Global.*;
import aBasis.House;
import aControl.Control;
import java.awt.Font;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.DefaultListModel;

/**
 *
 * @author b6dmin
 */
public class ControlPanel extends javax.swing.JPanel {

    private Control c;

    public void setControl(Control c) {
        this.c = c;
    }

    public void setTextLocale() {
        lblAsk.setText(rBundle.getString("LBL_ASK_TXT"));
        lblReceive.setText(rBundle.getString("LBL_RECEIVE_TXT"));
        btnStart.setText(rBundle.getString("BTN_START_TXT"));
    }

    DefaultListModel<String> askedForGiftModel = new DefaultListModel<>();
    DefaultListModel<String> receivedGiftModel = new DefaultListModel<>();

    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {
        initComponents();
        lstAsked.setModel(askedForGiftModel);
        lstReceived.setModel(receivedGiftModel);
    }

    public void fillAskList(List<String> list) {
        askedForGiftModel.clear();
        list.forEach((city) -> {
            askedForGiftModel.addElement(city);
        });
    }

    public void fillReceiveList(List<String> list) {
        receivedGiftModel.clear();
        list.forEach((city) -> {
            receivedGiftModel.addElement(city);
        });
    }

    public void setButtonActivity(boolean b) {
        btnStart.setEnabled(b);
    }

    private void useLanguage() {
        rBundle = ResourceBundle.getBundle(BUNDLE, locale);
        c.setLocaleBundle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnStart = new javax.swing.JButton();
        lblAsk = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAsked = new javax.swing.JList<>();
        lblReceive = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstReceived = new javax.swing.JList<>();
        rdbHU = new javax.swing.JRadioButton();
        rdbEN = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setMaximumSize(new java.awt.Dimension(250, 500));
        setMinimumSize(new java.awt.Dimension(250, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStart.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnStart.setText(" ");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 230, -1));

        lblAsk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAsk.setText("Kért");
        add(lblAsk, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, 230, -1));

        lstAsked.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstAsked);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, 230, -1));

        lblReceive.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblReceive.setText("Kapott");
        add(lblReceive, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 225, 230, -1));

        lstReceived.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstReceived);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 248, 230, -1));

        buttonGroup1.add(rdbHU);
        rdbHU.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdbHU.setText("magyar");
        rdbHU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aSource/Hungary.png"))); // NOI18N
        rdbHU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbHUActionPerformed(evt);
            }
        });
        add(rdbHU, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        rdbEN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbEN.setText("english");
        rdbEN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aSource/Great-britain.png"))); // NOI18N
        rdbEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbENActionPerformed(evt);
            }
        });
        add(rdbEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 460, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void rdbHUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbHUActionPerformed
        locale = new Locale("hu", "HU");
        rdbHU.setFont(rdbHU.getFont().deriveFont(Font.BOLD));
        rdbEN.setFont(rdbEN.getFont().deriveFont(Font.PLAIN));
        useLanguage();
    }//GEN-LAST:event_rdbHUActionPerformed

    private void rdbENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbENActionPerformed
        locale = new Locale("en", "GB");
        rdbHU.setFont(rdbHU.getFont().deriveFont(Font.PLAIN));
        rdbEN.setFont(rdbEN.getFont().deriveFont(Font.BOLD));
        useLanguage();
    }//GEN-LAST:event_rdbENActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        c.startSanktaTour();
    }//GEN-LAST:event_btnStartActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAsk;
    private javax.swing.JLabel lblReceive;
    private javax.swing.JList<String> lstAsked;
    private javax.swing.JList<String> lstReceived;
    private javax.swing.JRadioButton rdbEN;
    private javax.swing.JRadioButton rdbHU;
    // End of variables declaration//GEN-END:variables
}
