package aSurface;

import aBasis.Conference;
import aBasis.Participant;
import aControl.Control;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author KissJGabi
 */
public class SimulationPanel extends javax.swing.JPanel {

    private DefaultListModel<Participant> participantListModel
            = new DefaultListModel<>();
    private DefaultListModel<Conference> conferenceListModel
            = new DefaultListModel<>();

    private Control c;

    public void setControl(Control c) {
        this.c = c;
    }

    public SimulationPanel() {
        initComponents();
        lstParticipants.setModel(participantListModel);
        lstConferences.setModel(conferenceListModel);
        btnSort.setEnabled(false);
    }

    private void clearPanel() {
        participantListModel.clear();
        conferenceListModel.clear();
        lblDonation.setText("");
        lblScores.setText("");
        lblVotes.setText("");
        btnSort.setEnabled(false);
        btnVote.setEnabled(true);
    }

    public void participantList(List<Participant> list) {
        list.forEach((participant) -> {
            participantListModel.addElement(participant);
        });
    }

    public void conferencesList(List<Conference> list) {
        list.forEach((conference) -> {
            conferenceListModel.addElement(conference);
        });
    }

    public void donationLabel(int d) {
        lblDonation.setText("Az összes adomány ($): " + d);
    }

    public void votesLabel(int v) {
        lblVotes.setText("Az összes pont: " + v);
    }

    public void scoresLabel(int s) {
        lblScores.setText("Pontszám: " + s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstConferences = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstParticipants = new javax.swing.JList<>();
        lblDonation = new javax.swing.JLabel();
        lblScores = new javax.swing.JLabel();
        lblVotes = new javax.swing.JLabel();
        btnLoadFromDBase = new javax.swing.JButton();
        btnLoadFromFile = new javax.swing.JButton();
        btnVote = new javax.swing.JButton();
        btnSort = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setMinimumSize(new java.awt.Dimension(540, 360));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Konferenciák");
        jLabel1.setMaximumSize(new java.awt.Dimension(260, 17));
        jLabel1.setMinimumSize(new java.awt.Dimension(260, 17));
        jLabel1.setPreferredSize(new java.awt.Dimension(260, 17));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Résztvevők");
        jLabel2.setMaximumSize(new java.awt.Dimension(260, 17));
        jLabel2.setMinimumSize(new java.awt.Dimension(260, 17));
        jLabel2.setPreferredSize(new java.awt.Dimension(260, 17));

        jScrollPane1.setMinimumSize(new java.awt.Dimension(260, 23));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(260, 194));

        lstConferences.setModel(new javax.swing.AbstractListModel<Conference>() {
            Conference[] conferences;
            public int getSize() { return conferences.length; }
            public Conference getElementAt(int i) { return conferences[i]; }
        });
        lstConferences.setVisibleRowCount(12);
        lstConferences.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstConferencesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstConferences);

        jScrollPane2.setMinimumSize(new java.awt.Dimension(260, 23));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(260, 194));

        lstParticipants.setModel(new javax.swing.AbstractListModel<Participant>() {
            Participant[] participants;
            public int getSize() { return participants.length; }
            public Participant getElementAt(int i) { return participants[i]; }
        });
        lstParticipants.setVisibleRowCount(12);
        lstParticipants.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstParticipantsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstParticipants);

        lblDonation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDonation.setText("Az összes adomány ($):");

        lblScores.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblScores.setText("Pontszám:");

        lblVotes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblVotes.setText("Az összes pont:");

        btnLoadFromDBase.setText("DataBase");
        btnLoadFromDBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadFromDBaseActionPerformed(evt);
            }
        });

        btnLoadFromFile.setText("Fájl");
        btnLoadFromFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadFromFileActionPerformed(evt);
            }
        });

        btnVote.setText("Eredmények");
        btnVote.setMaximumSize(new java.awt.Dimension(160, 23));
        btnVote.setMinimumSize(new java.awt.Dimension(160, 23));
        btnVote.setPreferredSize(new java.awt.Dimension(160, 23));
        btnVote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoteActionPerformed(evt);
            }
        });

        btnSort.setText("Rendezés");
        btnSort.setMaximumSize(new java.awt.Dimension(160, 23));
        btnSort.setMinimumSize(new java.awt.Dimension(160, 23));
        btnSort.setPreferredSize(new java.awt.Dimension(160, 23));
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLoadFromDBase, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnLoadFromFile, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDonation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVotes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblScores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSort, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVote, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDonation)
                    .addComponent(lblScores))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblVotes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnVote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLoadFromDBase)
                        .addComponent(btnLoadFromFile))
                    .addComponent(btnSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadFromDBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadFromDBaseActionPerformed
        clearPanel();
        c.getDataFromDBase();
    }//GEN-LAST:event_btnLoadFromDBaseActionPerformed

    private void lstConferencesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstConferencesMouseClicked
        participantListModel.clear();
        lblScores.setText("");
        c.showParticipants(lstConferences.getSelectedValue());
    }//GEN-LAST:event_lstConferencesMouseClicked

    private void btnLoadFromFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadFromFileActionPerformed
        clearPanel();
        c.getDataFromFile();
    }//GEN-LAST:event_btnLoadFromFileActionPerformed

    private void btnVoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoteActionPerformed
        btnSort.setEnabled(true);
        btnVote.setEnabled(false);
        c.getVotes();
    }//GEN-LAST:event_btnVoteActionPerformed

    private void lstParticipantsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstParticipantsMouseClicked
        c.showScore(lstParticipants.getSelectedValue());
    }//GEN-LAST:event_lstParticipantsMouseClicked

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
        clearPanel();
        c.getVotes();
        c.sortConferences();
    }//GEN-LAST:event_btnSortActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoadFromDBase;
    private javax.swing.JButton btnLoadFromFile;
    private javax.swing.JButton btnSort;
    private javax.swing.JButton btnVote;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDonation;
    private javax.swing.JLabel lblScores;
    private javax.swing.JLabel lblVotes;
    private javax.swing.JList<Conference> lstConferences;
    private javax.swing.JList<Participant> lstParticipants;
    // End of variables declaration//GEN-END:variables
}
