/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aSurface;

import aBasis.City;
import static aBasis.Global.*;
import aControl.Control;
import java.awt.Font;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author b6dmin
 */
public class ControlPanel extends javax.swing.JPanel {

    private Control c;

    public void setControl(Control c) {
        this.c = c;
    }

    public void setTextLocale() {
        lblDeparture.setText(rBundle.getString("LBL_DEPARTURE_TXT"));
        lblDestination.setText(rBundle.getString("LBL_DESTINATION_TXT"));
        setPayText();
        btnSearch.setText(rBundle.getString("BTN_SEARCH_TXT"));
    }

    DefaultComboBoxModel<City> departureModel = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<City> destinationModel = new DefaultComboBoxModel<>();

    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {
        initComponents();
        comboDeparture.setModel(departureModel);
        comboDestination.setModel(destinationModel);
    }

    public void fillDepartureList(List<City> list) {
        list.forEach((city) -> {
            departureModel.addElement(city);
        });
    }

    public void fillDestinationList(List<City> list) {
        list.forEach((city) -> {
            destinationModel.addElement(city);
        });
    }

    public void setButtonActivity(boolean b) {
        btnSearch.setEnabled(b);
        comboDeparture.setEnabled(b);
        comboDestination.setEnabled(b);
    }

    public void setPayText() {
        if (to_pay == 0) {
            lblToPay.setText(" ");
        } else {
            if (locale.equals(new Locale("en", "GB"))) {
                double dummy = to_pay / CHANGE2FONT;
                lblToPay.setText(rBundle.getString("LBL_PAY_TXT")
                        + String.format("%6.2f", dummy) + " " + currency);
            }
            if (locale.equals(new Locale("hu", "HU"))) {
                lblToPay.setText(rBundle.getString("LBL_PAY_TXT")
                        + to_pay + " " + currency);
            }
        }
    }

    private void useLanguage() {
        rBundle = ResourceBundle.getBundle(BUNDLE, locale);
        c.setLocaleBundle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblDeparture = new javax.swing.JLabel();
        comboDeparture = new javax.swing.JComboBox<>();
        lblDestination = new javax.swing.JLabel();
        comboDestination = new javax.swing.JComboBox<>();
        rdbHU = new javax.swing.JRadioButton();
        rdbEN = new javax.swing.JRadioButton();
        lblToPay = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 153));
        setMaximumSize(new java.awt.Dimension(200, 600));
        setMinimumSize(new java.awt.Dimension(200, 600));
        setPreferredSize(new java.awt.Dimension(200, 600));

        lblDeparture.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDeparture.setText("Indulás:");

        comboDeparture.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboDeparture.setModel(new javax.swing.DefaultComboBoxModel<>(new City[] {  }));
        comboDeparture.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboDepartureItemStateChanged(evt);
            }
        });

        lblDestination.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDestination.setText("Érkezés:");

        comboDestination.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new City[] { }));
        comboDestination.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboDestinationItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rdbHU);
        rdbHU.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rdbHU.setText("magyar");
        rdbHU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aSource/Hungary.png"))); // NOI18N
        rdbHU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbHUActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbEN);
        rdbEN.setText("english");
        rdbEN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aSource/Great-britain.png"))); // NOI18N
        rdbEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbENActionPerformed(evt);
            }
        });

        lblToPay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblToPay.setText("Fizetendő:");

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearch.setText("Keress!");
        btnSearch.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aSource/locale.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDeparture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboDeparture, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDestination, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboDestination, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbHU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdbEN))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblToPay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDeparture)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDestination)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnSearch)
                .addGap(18, 18, 18)
                .addComponent(lblToPay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbHU)
                    .addComponent(rdbEN))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rdbHUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbHUActionPerformed
        locale = new Locale("hu", "HU");
        rdbHU.setFont(rdbHU.getFont().deriveFont(Font.BOLD));
        rdbEN.setFont(rdbEN.getFont().deriveFont(Font.PLAIN));
        useLanguage();
    }//GEN-LAST:event_rdbHUActionPerformed

    private void rdbENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbENActionPerformed
        locale = new Locale("en", "GB");
        rdbHU.setFont(rdbHU.getFont().deriveFont(Font.PLAIN));
        rdbEN.setFont(rdbEN.getFont().deriveFont(Font.BOLD));
        useLanguage();
    }//GEN-LAST:event_rdbENActionPerformed

    private void comboDepartureItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboDepartureItemStateChanged
        c.setDepartureCity((City) comboDeparture.getSelectedItem());
    }//GEN-LAST:event_comboDepartureItemStateChanged

    private void comboDestinationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboDestinationItemStateChanged
        c.setDestinationCity((City) comboDestination.getSelectedItem());
    }//GEN-LAST:event_comboDestinationItemStateChanged

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        c.startFly((City) departureModel.getSelectedItem(),
                (City) destinationModel.getSelectedItem());
    }//GEN-LAST:event_btnSearchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<City> comboDeparture;
    private javax.swing.JComboBox<City> comboDestination;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDeparture;
    private javax.swing.JLabel lblDestination;
    private javax.swing.JLabel lblToPay;
    private javax.swing.JRadioButton rdbEN;
    private javax.swing.JRadioButton rdbHU;
    // End of variables declaration//GEN-END:variables
}
