/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aSurface;

import static aBasis.Global.*;
import aControl.Control;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JComponent;

/**
 *
 * @author b6dmin
 */
public class GraphicPanel<T> extends javax.swing.JPanel {

    private final Image myImage
            = new ImageIcon(this.getClass().
                    getResource(imgGraphic)).getImage();
    private Control<T> c;

    public void setControl(Control<T> c) {
        this.c = c;
    }

    /**
     * Creates new form GraphicPanel
     */
    public GraphicPanel() {
        initComponents();
    }

    public void setComponent(JComponent fish, int kX, int kY) {
        fish.setLocation(kX, kY);
        this.add(fish);
        this.setComponentZOrder(fish, 0);
    }

    public void deleteComponent(JComponent fish) {
        this.remove(fish);
        this.repaint();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(myImage, 0, 0, this.getWidth(), this.getHeight(), null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMinimumSize(new java.awt.Dimension(700, 460));
        setPreferredSize(new java.awt.Dimension(700, 460));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        c.hitFish(evt.getX(), evt.getY());
    }//GEN-LAST:event_formMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
