/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aSurface;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.text.DateFormat;
import java.util.Date;

/**
 *
 * @author b6dmin
 */
public class ClockJPanel extends javax.swing.JPanel implements Runnable {

    private final int LETTER_HEGHT = 20;

    private Font font;
    private DateFormat dateFormat;
    private String currentTime;

    private Thread thread;

    private boolean online = true;

    private int panelWidth;
    private int panelHeight;

    public void setPanelWidth(int panelWidth) {
        this.panelWidth = panelWidth;
    }

    public void setPanelHeight(int panelHeight) {
        this.panelHeight = panelHeight;
    }

    /**
     * Creates new form ClockJPanel
     */
    public ClockJPanel() {
        initComponents();
        font = new Font("Times", Font.BOLD, LETTER_HEGHT);
        dateFormat = DateFormat.getTimeInstance();
        currentTime = dateFormat.format(new Date());
    }

    public void startClock() {
        if (thread == null) {
            thread = new Thread(this);
            thread.start();
        }
    }

    @Override
    public void run() {
        int timeUnit = 1000;
        while (online) {
            currentTime = dateFormat.format(new Date());
            try {
                Thread.sleep(timeUnit);
            } catch (InterruptedException ex) {
                ex.getMessage();
            }
            this.repaint();
        }
    }

    private Dimension textSize(Graphics g, String text) {
        FontMetrics metrics = g.getFontMetrics(font);
        return new Dimension(metrics.stringWidth(text), metrics.getHeight());
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.setFont(font);
        g.setColor(Color.BLUE);
        String str = "A pontos idő: " + currentTime;
        int textWidth = textSize(g, str).width;
        int textHeight = textSize(g, str).height;
        int y = panelHeight / 2;
        int x = (panelWidth - textWidth) / 2;
        g.drawString(str, x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMinimumSize(new java.awt.Dimension(200, 100));
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
