/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aSurface;

import static aBasis.Global.*;
import aControl.Control;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author b6dmin
 */
public class GraphityPanel extends javax.swing.JPanel {

    private final Image mainImage
            = new ImageIcon(this.getClass().
                    getResource(GRAPHITY_BG)).getImage();
    private final Image startImage
            = new ImageIcon(this.getClass().
                    getResource(START_BG)).getImage();
    private final Image finalImage
            = new ImageIcon(this.getClass().
                    getResource(FINAL_BG)).getImage();
    private Control c;

    public void setControl(Control c) {
        this.c = c;
    }

    public void setup() {
        System.out.println("graphityPanel: "
                + this.getWidth() + "x" + this.getHeight());
    }

    /**
     * Creates new form GraphityPanel
     */
    public GraphityPanel() {
        System.out.println("GraphityPanel()");
        initComponents();
        super.setPreferredSize(new Dimension(GRAPHITY_WIDTH, GRAPHITY_HEIGHT));
    }

    @Override
    protected void paintComponent(Graphics g) {
        //System.out.println("GraphityPanel.paintComponent > " + state);
        super.paintComponent(g);
        switch (state) {
            case PROLOG: {
                g.drawImage(startImage, 0, 0,
                        this.getWidth(), this.getHeight(), this);
                String str = rBundle.getString("SKI_RESORT_TXT");
                g.setFont(new Font("Serif", Font.BOLD, 31));
                int width = g.getFontMetrics().stringWidth(str);
                g.drawString(str,
                        (GRAPHITY_WIDTH - width) / 2,
                        GRAPHITY_HEIGHT / 6);
                break;
            }
            case FINALE: {
                g.drawImage(finalImage, 0, 0,
                        this.getWidth(), this.getHeight(), this);
                break;
            }
            default: {
                g.drawImage(mainImage, 0, 0,
                        this.getWidth(), this.getHeight(), this);
            }
        }
        if (c != null) {
            c.drawGraphity(g);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 102, 0));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        c.clickOnGraphity(evt.getX(), evt.getY(), evt.getButton());
    }//GEN-LAST:event_formMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        c.startProlog(evt.getX(), evt.getY());
    }//GEN-LAST:event_formMouseDragged

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        if (state == PROCESS_STATE.PROLOG) {
            c.finishProlog();
        }
    }//GEN-LAST:event_formMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
