/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aSurface;

import aControl.Control;
import java.awt.Graphics;

/**
 *
 * @author b6dmin
 */
public class MandelbrotPanel extends javax.swing.JPanel implements Runnable {

    private final int SLEEP = 1000;
    private final int STEP = 25;
    private final double ZOOM_MIN = 500;
    private final double ZOOM_MAX = 1000;
    private Thread myThread;
    private boolean isRunning = true;

    private double zoom = ZOOM_MIN - STEP;
    private Control c;

    public double getZOOM_MIN() {
        return ZOOM_MIN;
    }

    public double getZOOM_MAX() {
        return ZOOM_MAX;
    }

    public void setControl(Control control) {
        this.c = control;
    }

    /**
     * Creates new form MandelbrotPanel
     */
    public MandelbrotPanel() {
        initComponents();
    }

    @Override
    public void run() {
        while (isRunning) {
            while (zoom < ZOOM_MAX) {
                try {
                    Thread.sleep(SLEEP);
                } catch (InterruptedException ex) {
                    ex.getMessage();
                }
                zoom += STEP;
                this.repaint();
            }
            while (zoom > ZOOM_MIN) {
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    ex.getMessage();
                }
                zoom -= STEP;
                this.repaint();
            }
        }
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        c.drawMandelbrot(g, zoom);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        if (myThread == null) {
            myThread = new Thread(this);
            myThread.start();
        }
    }//GEN-LAST:event_formAncestorAdded

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
