/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aSurface;

import aControl.Control;
import java.util.ResourceBundle;

/**
 *
 * @author b6dmin
 */
public class Warriors extends javax.swing.JPanel {

    private Control c;

    public void setControl(Control c) {
        this.c = c;
    }

    /**
     * Creates new form Warriors
     */
    public Warriors() {
        initComponents();
    }

    public void setTextLocale(ResourceBundle bundle) {
        lblFighter.setText(bundle.getString("LBL_FIGHTER"));
        btnFight.setText(bundle.getString("BTN_FIGHT"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFighter = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstFighter = new javax.swing.JList<>();
        btnFight = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 255, 204));

        lblFighter.setBackground(new java.awt.Color(153, 255, 153));
        lblFighter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFighter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFighter.setText("Harcosok");

        lstFighter.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstFighter);

        btnFight.setText("Csatára fel!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(lblFighter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFight, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFighter)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnFight)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFight;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFighter;
    private javax.swing.JList<String> lstFighter;
    // End of variables declaration//GEN-END:variables
}
