/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aSurface;

import aControl.Control;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;

/**
 *
 * @author linuxuser
 */
public class Welcome extends javax.swing.JPanel {

    private String imgSrc = "/images/hello_wien.png";
    private Image myImage
            = new ImageIcon(this.getClass().
                    getResource(imgSrc)).getImage();
    private Control c;

    public void setControl(Control c) {
        this.c = c;
    }

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
    }

    public void setTextLocale(ResourceBundle bundle) {
        btnONOFF.setText(bundle.getString("BTN_ONOFF"));
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(myImage, 0, 0, this.getWidth(), this.getHeight(), null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnONOFF = new javax.swing.JButton();

        btnONOFF.setText("Zene KI/BE");
        btnONOFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnONOFFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(619, Short.MAX_VALUE)
                                .addComponent(btnONOFF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(601, Short.MAX_VALUE)
                                .addComponent(btnONOFF)
                                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnONOFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnONOFFActionPerformed
        c.playOnOff();
    }//GEN-LAST:event_btnONOFFActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnONOFF;
    // End of variables declaration//GEN-END:variables
}
