CREATE TABLE RESZTVEVOK ( id int not null primary key, 
                              nev varchar(40), 
                              penz int);

INSERT INTO RESZTVEVOK VALUES(1,'Baranyai János',400);
INSERT INTO RESZTVEVOK VALUES(2,'Zala György',800);
INSERT INTO RESZTVEVOK VALUES(3,'Bryan Smith',1100);
INSERT INTO RESZTVEVOK VALUES(4,'Csongrádi Kata',500);
INSERT INTO RESZTVEVOK VALUES(5,'Abdul Aziz',700);
INSERT INTO RESZTVEVOK VALUES(6,'Franklin Taylor',1200);
INSERT INTO RESZTVEVOK VALUES(7,'Fejér Anna',400);
INSERT INTO RESZTVEVOK VALUES(8,'William Clark',900);
INSERT INTO RESZTVEVOK VALUES(9,'Tsung-Dao Lee',1100);
INSERT INTO RESZTVEVOK VALUES(10,'Zou Xuan',700);
INSERT INTO RESZTVEVOK VALUES(11,'Békési Judit',1200);
INSERT INTO RESZTVEVOK VALUES(12,'Michael Rossi',1150);
INSERT INTO RESZTVEVOK VALUES(13,'Isontalon Antti',1300);
INSERT INTO RESZTVEVOK VALUES(14,'Joseph Fischer',1200);
INSERT INTO RESZTVEVOK VALUES(15,'Yamato Fujimoto',1500);
INSERT INTO RESZTVEVOK VALUES(16,'Bernald Linder',600);
INSERT INTO RESZTVEVOK VALUES(17,'Carl Oberfrank',1300);
