CREATE TABLE FOCI.CSAPATOK ( id int not null primary key, 
                            nev varchar(40));

INSERT INTO FOCI.CSAPATOK VALUES(1,'Portugália');
INSERT INTO FOCI.CSAPATOK VALUES(2,'Franciaország');
INSERT INTO FOCI.CSAPATOK VALUES(3,'Spanyolország');
INSERT INTO FOCI.CSAPATOK VALUES(4,'Ausztria');
INSERT INTO FOCI.CSAPATOK VALUES(5,'Németország');
INSERT INTO FOCI.CSAPATOK VALUES(6,'Románia');
INSERT INTO FOCI.CSAPATOK VALUES(7,'Lengyelország');
INSERT INTO FOCI.CSAPATOK VALUES(8,'Horvátország');
INSERT INTO FOCI.CSAPATOK VALUES(9,'Olaszország');
INSERT INTO FOCI.CSAPATOK VALUES(10,'Anglia');
INSERT INTO FOCI.CSAPATOK VALUES(11,'Belgium');
INSERT INTO FOCI.CSAPATOK VALUES(12,'Magyarország');


