CREATE TABLE PALYAZOK ( id int not null primary key, 
                              nev varchar(40), 
                              kod varchar(40));

INSERT INTO PALYAZOK VALUES(1,'Harmat Péter','HAPEABC.PTE');
INSERT INTO PALYAZOK VALUES(2,'Balogh Lajos','BALAABC.PTE');
INSERT INTO PALYAZOK VALUES(3,'Tamás Judit','TAJUABC.PTE');
INSERT INTO PALYAZOK VALUES(4,'Gergely János','GEJAABC.PTE');
INSERT INTO PALYAZOK VALUES(5,'Orosz Anna','ORANABC.PTE');
INSERT INTO PALYAZOK VALUES(6,'Hegedûs Péter','HEPEABC.PTE');
INSERT INTO PALYAZOK VALUES(7,'Kalmár Hajnalka','KAHAABC.PTE');
INSERT INTO PALYAZOK VALUES(8,'Elekes Judit','ELJUABC.PTE');
INSERT INTO PALYAZOK VALUES(9,'Kamarás Dezsõ','KADEABC:PTE');
INSERT INTO PALYAZOK VALUES(10,'Fodor Tamás','FOTAABC.PTE');
