package aSurface;

import aBasis.Alcohol;
import aBasis.Drink;
import aBasis.SortableListModel;
import aControl.Control;
import com.sun.javafx.collections.SortableList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author KissJGabi
 */
public class TavernPanel extends javax.swing.JPanel {

    private SortableListModel<Drink> drinkListModel
            = new SortableListModel<Drink>();
    private SortableListModel<Drink> orderedListModel
            = new SortableListModel<>();

    private Control control;

    public void setControl(Control c) {
        this.control = c;
    }

    public TavernPanel() {
        initComponents();
        lstDrink.setModel(drinkListModel);
        lstOrdered.setModel(orderedListModel);
    }

    public void listDrink(List<Drink> list) {
        drinkListModel.clear();
        list.forEach((drink) -> {
            drinkListModel.addElement(drink);
        });
    }

    public void listOrdered() {
        lstOrdered.repaint();
    }

    public void sortingBy() {
        drinkListModel.sort();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstOrdered = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstDrink = new javax.swing.JList<>();
        btnFizet = new javax.swing.JButton();
        lblAlcoholPercent = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aSurface/nyil.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lstOrdered.setModel(new javax.swing.AbstractListModel<Drink>() {
            Drink[] d;
            public int getSize() { return d.length; }
            public Drink getElementAt(int i) { return d[i]; }
        });
        lstOrdered.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstOrdered.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstOrderedValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstOrdered);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Választott italok");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Itallap");

        lstDrink.setModel(new javax.swing.AbstractListModel<Drink>() {
            Drink[] d;
            public int getSize() { return d.length; }
            public Drink getElementAt(int i) { return d[i]; }
        });
        jScrollPane2.setViewportView(lstDrink);

        btnFizet.setText("Fizet");
        btnFizet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFizetActionPerformed(evt);
            }
        });

        lblAlcoholPercent.setText("@2019 by Commondoor 64 g");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAlcoholPercent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFizet, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFizet)
                    .addComponent(lblAlcoholPercent))
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("nyíl clicked");
        List<Drink> choosedDrinks = lstDrink.getSelectedValuesList();
        Drink choosedDrink;
        for (Drink d : choosedDrinks) {
            control.administrate(d);
            choosedDrink = d instanceof Alcohol
                    ? new Alcohol(d.getNAME(), d.getCODE(),
                            d.getPRICE(), ((Alcohol) d).getBRAND(),
                            ((Alcohol) d).getAV(), d.getUNIT())
                    : new Drink(d.getNAME(), d.getCODE(),
                            d.getPRICE(), d.getUNIT());
            if (!(orderedListModel.contains(choosedDrink))) {
                choosedDrink.oderDrink();
                orderedListModel.addElement(choosedDrink);
            } else {
                int index = orderedListModel.indexOf(choosedDrink);
                orderedListModel.getElementAt(index).oderDrink();
            }
        }
        listOrdered();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnFizetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFizetActionPerformed
        int sum = 0;
        for (int ii = 0; ii < orderedListModel.getSize(); ii++) {
            sum += orderedListModel.getElementAt(ii).orderPrice();
        }
        lblAlcoholPercent.setText("Fizetendő: " + sum + "Ft");
        orderedListModel.clear();
        lstOrdered.repaint();
        lstDrink.clearSelection();
    }//GEN-LAST:event_btnFizetActionPerformed

    private void lstOrderedValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstOrderedValueChanged
        Drink d = lstOrdered.getSelectedValue();
        if (d != null) {
            if (d instanceof Alcohol) {
                lblAlcoholPercent.setText("A választott ital alkoholfoka: "
                        + ((Alcohol) d).getAV() + " fok");
            } else {
                lblAlcoholPercent.setText("A választott ital alkohol mentes");
            }
        }
    }//GEN-LAST:event_lstOrderedValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFizet;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAlcoholPercent;
    private javax.swing.JList<Drink> lstDrink;
    private javax.swing.JList<Drink> lstOrdered;
    // End of variables declaration//GEN-END:variables
}
