package aSurface;

import aBasis.AudioBook;
import aBasis.Book;
import aBasis.PaperBook;
import aControl.Control;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author KissJGabi
 */
public class SimulationPanel extends javax.swing.JPanel {

    private DefaultListModel<PaperBook> pBookListModel
            = new DefaultListModel<>();
    private DefaultListModel<AudioBook> aBookListModel
            = new DefaultListModel<>();
    private DefaultListModel<Book> lendingsListModel
            = new DefaultListModel<>();

    private Control control;

    public SimulationPanel() {
        initComponents();
        lstPaperBooks.setModel(pBookListModel);
        lstAudioBooks.setModel(aBookListModel);
        lstLendedBooks.setModel(lendingsListModel);
    }

    public void setControl(Control c) {
        this.control = c;
    }

    private void clearSelections() {
        lblRemainingTime.setText("");
        lstPaperBooks.clearSelection();
        lstAudioBooks.clearSelection();
    }

    private void clearPanel() {
        pBookListModel.clear();
        aBookListModel.clear();
        lendingsListModel.clear();
        lblMain.setText("");
        lblRemainingTime.setText("");
    }

    public void paperBookList(List<PaperBook> list) {
        list.forEach((p) -> {
            pBookListModel.addElement(p);
        });
    }

    public void audioBookList(List<AudioBook> list) {
        list.forEach((a) -> {
            aBookListModel.addElement(a);
        });
    }

    public void lendedBookList(List<Book> list) {
        lendingsListModel.clear();
        list.forEach((p) -> {
            lendingsListModel.addElement(p);
        });
    }

    public void mainLabel(int d) {
        lblMain.setText("B6sics könyvtár (az olvasás korának " + d + ". napja)");
    }

    public void remainingTimeLabel(int r) {
        lblRemainingTime.setText("A kölcsönzési időből hátra van: " + r + " nap");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMain = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPaperBooks = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstLendedBooks = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstAudioBooks = new javax.swing.JList<>();
        btnLendingPaperBook = new javax.swing.JButton();
        btnLendingAudioBook = new javax.swing.JButton();
        btnTakBack = new javax.swing.JButton();
        lblRemainingTime = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnNewDay = new javax.swing.JButton();
        btnRestart = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        lblMain.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMain.setText("B6sics könyvtár (az olvasás korának 1. napja)");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Könyvek");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hangos könyvek");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Kölcsönzött könyvek");

        jScrollPane1.setMinimumSize(new java.awt.Dimension(270, 130));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(270, 389));

        lstPaperBooks.setModel(new javax.swing.AbstractListModel<PaperBook>() {
            PaperBook[] p;
            public int getSize() { return p.length; }
            public PaperBook getElementAt(int i) { return p[i]; }
        });
        lstPaperBooks.setVisibleRowCount(16);
        jScrollPane1.setViewportView(lstPaperBooks);

        jScrollPane3.setMinimumSize(new java.awt.Dimension(270, 130));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(270, 389));

        lstLendedBooks.setModel(new javax.swing.AbstractListModel<Book>() {
            Book[] b;
            public int getSize() { return b.length; }
            public Book getElementAt(int i) { return b[i]; }
        });
        lstLendedBooks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstLendedBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstLendedBooksMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(lstLendedBooks);

        jScrollPane2.setMinimumSize(new java.awt.Dimension(270, 130));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(270, 389));

        lstAudioBooks.setModel(new javax.swing.AbstractListModel<AudioBook>() {
            AudioBook[] a;
            public int getSize() { return a.length; }
            public AudioBook getElementAt(int i) { return a[i]; }
        });
        jScrollPane2.setViewportView(lstAudioBooks);

        btnLendingPaperBook.setText("Kölcsönöz");
        btnLendingPaperBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLendingPaperBookActionPerformed(evt);
            }
        });

        btnLendingAudioBook.setText("Kölcsönöz");
        btnLendingAudioBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLendingAudioBookActionPerformed(evt);
            }
        });

        btnTakBack.setText("Visszahoz");
        btnTakBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTakBackActionPerformed(evt);
            }
        });

        lblRemainingTime.setText("A kölcsönzési időből hátra van:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("@2019 by Commondoor 64");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btnNewDay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNewDay.setText("Egy új nap");
        btnNewDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewDayActionPerformed(evt);
            }
        });

        btnRestart.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRestart.setText("Restart");
        btnRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLendingPaperBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNewDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLendingAudioBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRestart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblRemainingTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnTakBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMain)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLendingPaperBook)
                    .addComponent(btnLendingAudioBook)
                    .addComponent(lblRemainingTime))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTakBack)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(btnNewDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRestart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lstLendedBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstLendedBooksMouseClicked
        control.countRemainingTime(lstLendedBooks.getSelectedValue());
    }//GEN-LAST:event_lstLendedBooksMouseClicked

    private void btnRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestartActionPerformed
        clearPanel();
        control.restart();
    }//GEN-LAST:event_btnRestartActionPerformed

    private void btnLendingPaperBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLendingPaperBookActionPerformed
        control.lendingPaperBook(lstPaperBooks.getSelectedValuesList());
        clearSelections();
    }//GEN-LAST:event_btnLendingPaperBookActionPerformed

    private void btnLendingAudioBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLendingAudioBookActionPerformed
        control.lendingAudioBook(lstAudioBooks.getSelectedValuesList());
        clearSelections();
    }//GEN-LAST:event_btnLendingAudioBookActionPerformed

    private void btnNewDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewDayActionPerformed
        clearSelections();
        control.aNewDayIsComing();
    }//GEN-LAST:event_btnNewDayActionPerformed

    private void btnTakBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTakBackActionPerformed
        clearSelections();
        control.takeBookBack(lstLendedBooks.getSelectedValue());
    }//GEN-LAST:event_btnTakBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLendingAudioBook;
    private javax.swing.JButton btnLendingPaperBook;
    private javax.swing.JButton btnNewDay;
    private javax.swing.JButton btnRestart;
    private javax.swing.JButton btnTakBack;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblMain;
    private javax.swing.JLabel lblRemainingTime;
    private javax.swing.JList<AudioBook> lstAudioBooks;
    private javax.swing.JList<Book> lstLendedBooks;
    private javax.swing.JList<PaperBook> lstPaperBooks;
    // End of variables declaration//GEN-END:variables
}
