/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package surface;

import basis.Husband;
import basis.Match;
import basis.ThePair;
import basis.Wife;
import control.Control;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author KissJGabi
 */
public class MatchPanel extends javax.swing.JPanel {

    private DefaultListModel<ThePair> pairListModel = new DefaultListModel<>();
    private DefaultListModel<Husband> husbandListModel = new DefaultListModel<>();
    private DefaultListModel<Wife> wifeListModel = new DefaultListModel<>();
    private Control control;

    /**
     * Creates new form MatchPanel
     */
    public MatchPanel() {
        initComponents();
        lstPairs.setModel(pairListModel);
        lstHusbands.setModel(husbandListModel);
        lstWives.setModel(wifeListModel);
    }

    public void showDatas(List<ThePair> pairs) {
        pairListModel.clear();
        husbandListModel.clear();
        wifeListModel.clear();
        for (ThePair pair : pairs) {
            pairListModel.addElement(pair);
            husbandListModel.addElement(pair.getHUSBAND());
            wifeListModel.addElement(pair.getWIFE());
        }
    }

    public void writeResults(double average, int sum) {
        if (average > -1) {
            lblAverageBeer.setText(String.format("Átlagosan %5.2f sor fogyott",
                    average));
        } else {
            lblAverageBeer.setText("Nincs adat");
        }
        lblSumOfLeasureTime.setText("Összesen " + sum + " perc szabadidővel rendelkeztek");
    }

    public void writeMatch(Match match) {
        lblMatch.setText(match.toString());
    }

    public void setControl(Control c) {
        this.control = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMatch = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstHusbands = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstWives = new javax.swing.JList<>();
        btnMatch = new javax.swing.JButton();
        lblAverageBeer = new javax.swing.JLabel();
        lblSumOfLeasureTime = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstPairs = new javax.swing.JList<>();

        setMaximumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));

        lblMatch.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblMatch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMatch.setText("Mérkőzés");

        jLabel2.setText("Házaspárok");

        jLabel3.setText("Férjek");

        jLabel4.setText("Feleségek");

        jScrollPane2.setPreferredSize(new java.awt.Dimension(200, 330));

        lstHusbands.setModel(new javax.swing.AbstractListModel<Husband>() {
            Husband[] husbands;
            public int getSize() { return husbands.length; }
            public Husband getElementAt(int i) { return husbands[i]; }
        });
        jScrollPane2.setViewportView(lstHusbands);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(240, 330));

        lstWives.setModel(new javax.swing.AbstractListModel<Wife>() {
            Wife[] wives;
            public int getSize() { return wives.length; }
            public Wife getElementAt(int i) { return wives[i]; }
        });
        jScrollPane3.setViewportView(lstWives);

        btnMatch.setText("Mérkőzés");
        btnMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatchActionPerformed(evt);
            }
        });

        lblAverageBeer.setText("Átlagos sörfogyasztás");

        lblSumOfLeasureTime.setText("Összes szabadidő");

        jScrollPane4.setPreferredSize(new java.awt.Dimension(200, 330));

        lstPairs.setModel(new javax.swing.AbstractListModel<ThePair>() {
            ThePair[] pairs;
            public int getSize() { return pairs.length; }
            public ThePair getElementAt(int i) { return pairs[i]; }
        });
        jScrollPane4.setViewportView(lstPairs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnMatch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAverageBeer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSumOfLeasureTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblMatch)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMatch)
                    .addComponent(lblAverageBeer)
                    .addComponent(lblSumOfLeasureTime))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatchActionPerformed
        control.match();
    }//GEN-LAST:event_btnMatchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMatch;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAverageBeer;
    private javax.swing.JLabel lblMatch;
    private javax.swing.JLabel lblSumOfLeasureTime;
    private javax.swing.JList<Husband> lstHusbands;
    private javax.swing.JList<ThePair> lstPairs;
    private javax.swing.JList<Wife> lstWives;
    // End of variables declaration//GEN-END:variables
}
