package surface;

import basis.BallGuest;
import basis.SongTrack;
import control.Control;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author KissJGabi
 */
public class ModelingPanel extends javax.swing.JPanel {

    private DefaultListModel<BallGuest> guestModel
            = new DefaultListModel<>();
    private DefaultListModel<SongTrack> songModel
            = new DefaultListModel<>();
    private DefaultListModel<SongTrack> wishListModel
            = new DefaultListModel<>();
    private DefaultListModel<BallGuest> bestDancerModel
            = new DefaultListModel<>();

    public void setControl(Control c) {
        this.c = c;
    }

    private Control c;

    public ModelingPanel() {
        initComponents();
        lstBallGuest.setModel(guestModel);
        lstSong.setModel(songModel);
        lstWishes.setModel(wishListModel);
        lstBestDancer.setModel(bestDancerModel);
    }

    public void showDatas(List<BallGuest> ballGuests, List<SongTrack> songs) {
        showBallGuest(ballGuests);
        songModel.clear();
        songs.forEach((song) -> {
            songModel.addElement(song);
        });
    }

    public void showBallGuest(List<BallGuest> ballGuests) {
        guestModel.clear();
        ballGuests.forEach((bg) -> {
            guestModel.addElement(bg);
        });
    }

    public void showBestDancers(List<BallGuest> bestDancers) {
        bestDancerModel.clear();
        bestDancers.forEach((bd) -> {
            bestDancerModel.addElement(bd);
        });
    }

    public void showGuestName(String name) {
        lblWishes.setText(name);
    }

    public void deleteSongList() {
        wishListModel.clear();
    }

    public void showSongs(List<SongTrack> songTracks) {
        deleteSongList();
        songTracks.forEach((s) -> {
            wishListModel.addElement(s);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstBallGuest = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstSong = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstWishes = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstBestDancer = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblWishes = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnNewTurn = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(600, 650));
        setPreferredSize(new java.awt.Dimension(600, 650));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gólyabál");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(280, 280));

        lstBallGuest.setModel(new javax.swing.AbstractListModel<BallGuest>() {
            BallGuest[] ballGuests;
            public int getSize() { return ballGuests.length; }
            public BallGuest getElementAt(int i) { return ballGuests[i]; }
        });
        lstBallGuest.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstBallGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstBallGuestMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstBallGuest);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(280, 280));

        lstSong.setModel(new javax.swing.AbstractListModel<SongTrack>() {
            SongTrack[] songTracks;
            public int getSize() { return songTracks.length; }
            public SongTrack getElementAt(int i) { return songTracks[i]; }
        });
        jScrollPane2.setViewportView(lstSong);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(280, 130));

        lstWishes.setModel(new javax.swing.AbstractListModel<SongTrack>() {
            SongTrack[] songTracks;
            public int getSize() { return songTracks.length; }
            public SongTrack getElementAt(int i) { return songTracks[i]; }
        });
        jScrollPane3.setViewportView(lstWishes);

        jScrollPane4.setPreferredSize(new java.awt.Dimension(280, 130));

        lstBestDancer.setModel(new javax.swing.AbstractListModel<BallGuest>() {
            BallGuest[] ballGuests;
            public int getSize() { return ballGuests.length; }
            public BallGuest getElementAt(int i) { return ballGuests[i]; }
        });
        jScrollPane4.setViewportView(lstBestDancer);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bálozók");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Választható zeneszámok");

        lblWishes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblWishes.setText("XY válaszása:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("A legtöbbet táncolók:");

        btnNewTurn.setText("Új forduló");
        btnNewTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewTurnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblWishes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNewTurn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnNewTurn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWishes)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewTurnActionPerformed
        c.ballSimulation();
    }//GEN-LAST:event_btnNewTurnActionPerformed

    private void lstBallGuestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstBallGuestMouseClicked
        BallGuest ballGuest = (BallGuest) lstBallGuest.getSelectedValue();
        if (ballGuest != null) {
            c.songWish(ballGuest);
        }
    }//GEN-LAST:event_lstBallGuestMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewTurn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblWishes;
    private javax.swing.JList<BallGuest> lstBallGuest;
    private javax.swing.JList<BallGuest> lstBestDancer;
    private javax.swing.JList<SongTrack> lstSong;
    private javax.swing.JList<SongTrack> lstWishes;
    // End of variables declaration//GEN-END:variables
}
