/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aSurface;

import static aBasis.Global.*;
import aControl.Control;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author b6dmin
 */
public class ControlPanel extends javax.swing.JPanel {

    private final Image witchImage
            = new ImageIcon(this.getClass().
                    getResource(WITCH)).getImage();
    private Control c;

    public void setControl(Control c) {
        this.c = c;
    }

    public void setTextLocale() {
        lblPlayer.setText(rBundle.getString("LBL_LIST_TXT"));
        lblGoalShooter.setText(rBundle.getString("LBL_WITCH_TXT"));
        btnNewRound.setText(rBundle.getString("BTN_START_TXT"));
    }

    public void setup() {
        System.out.println("controlPanel: "
                + this.getWidth() + "x" + this.getHeight());
        setButtonActivity(false);
    }

    DefaultListModel<String> listModel = new DefaultListModel<>();
    DefaultListModel<String> goalModel = new DefaultListModel<>();

    /**
     * Creates new form ControlForm
     */
    public ControlPanel() {
        System.out.println("ControlPanel()");
        initComponents();
        super.setPreferredSize(new Dimension(CONTROL_WIDTH, CONTROL_HEIGHT));
        lstPlayer.setModel(listModel);
        lstGoalShooters.setModel(goalModel);
    }

    public void setButtonActivity(boolean b) {
        btnNewRound.setEnabled(b);
    }

    public void clearLists() {
        goalModel.clear();
        listModel.clear();
    }

    public void fillPeopleList(String str) {
        listModel.addElement(str);
    }

    public void fillWitchList(String str) {
        goalModel.addElement(str);
    }

    private void useLanguage() {
        rBundle = ResourceBundle.getBundle(BUNDLE, locale);
        c.setLocaleBundle();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        switch (state) {
            case PROLOG: {
                break;
            }
            case FINALE: {
                g.drawImage(witchImage, 0, CONTROL_HEIGHT / 4,
                        this.getWidth(), this.getHeight() / 2, this);
                break;
            }
            default: {

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rdbHU = new javax.swing.JRadioButton();
        rdbEN = new javax.swing.JRadioButton();
        lblPlayer = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPlayer = new javax.swing.JList<>();
        lblGoalShooter = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstGoalShooters = new javax.swing.JList<>();
        btnNewRound = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        buttonGroup1.add(rdbHU);
        rdbHU.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdbHU.setSelected(true);
        rdbHU.setText("magyar");
        rdbHU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aSource/Hungary.png"))); // NOI18N
        rdbHU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbHUActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbEN);
        rdbEN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbEN.setText("english");
        rdbEN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aSource/Great-britain.png"))); // NOI18N
        rdbEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbENActionPerformed(evt);
            }
        });

        lblPlayer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPlayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayer.setText("jLabel1");

        lstPlayer.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstPlayer.setVisibleRowCount(10);
        jScrollPane1.setViewportView(lstPlayer);

        lblGoalShooter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGoalShooter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGoalShooter.setText("jLabel2");

        lstGoalShooters.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstGoalShooters.setVisibleRowCount(10);
        jScrollPane2.setViewportView(lstGoalShooters);

        btnNewRound.setText("jButton1");
        btnNewRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRoundActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbHU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                        .addComponent(rdbEN))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addComponent(lblPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGoalShooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewRound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPlayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblGoalShooter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNewRound)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbHU)
                    .addComponent(rdbEN))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rdbHUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbHUActionPerformed
        locale = new Locale("hu", "HU");
        rdbHU.setFont(rdbHU.getFont().deriveFont(Font.BOLD));
        rdbEN.setFont(rdbEN.getFont().deriveFont(Font.PLAIN));
        useLanguage();
    }//GEN-LAST:event_rdbHUActionPerformed

    private void rdbENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbENActionPerformed
        locale = new Locale("en", "GB");
        rdbHU.setFont(rdbHU.getFont().deriveFont(Font.PLAIN));
        rdbEN.setFont(rdbEN.getFont().deriveFont(Font.BOLD));
        useLanguage();
    }//GEN-LAST:event_rdbENActionPerformed

    private void btnNewRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRoundActionPerformed
        c.buildChair();
    }//GEN-LAST:event_btnNewRoundActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewRound;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblGoalShooter;
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JList<String> lstGoalShooters;
    private javax.swing.JList<String> lstPlayer;
    private javax.swing.JRadioButton rdbEN;
    private javax.swing.JRadioButton rdbHU;
    // End of variables declaration//GEN-END:variables
}
