/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aSurface;

import static aBasis.Global.*;
import aControl.Control;
import java.awt.Dimension;
import java.awt.Font;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.DefaultListModel;

/**
 *
 * @author b6dmin
 */
public class ControlPanel extends javax.swing.JPanel {

    private Control c;

    private int score = 0;

    public void setScore(int score) {
        this.score = score;
    }

    private String myScore() {
        if (score > 0) {
            return " " + score + " " + rBundle.getString("SCORE_TXT");
        } else {
            return "       ";
        }
    }

    public void setControl(Control c) {
        this.c = c;
    }

    public void setTextLocale() {
        lblList.setText(rBundle.getString("LBL_FLOWERS_TXT"));
        lblScores.setText(rBundle.getString("LBL_SCORES_TXT") + myScore());
        btnStart.setText(rBundle.getString("BTN_START_TXT"));
    }

    public void setup() {
        System.out.println("controlPanel: "
                + this.getWidth() + "x" + this.getHeight());
        setButtonActivity(false);
    }

    DefaultListModel<String> listModel = new DefaultListModel<>();

    /**
     * Creates new form ControlForm
     */
    public ControlPanel() {
        System.out.println("ControlPanel()");
        super.setPreferredSize(new Dimension(CONTROL_WIDTH, CONTROL_HEIGHT));
        initComponents();
        lstList.setModel(listModel);
    }

    public void setButtonStart(boolean b) {
        btnStart.setEnabled(b);
    }

    public void setButtonActivity(boolean b) {
        setButtonStart(b);
    }

    public void fillList(String str) {
        listModel.addElement(str);
    }

    public void fillList(String str, int ii) {
        listModel.add(ii, str);
    }

    public void deleteFromList(int ii) {
        listModel.removeElementAt(ii);
    }

    private void useLanguage() {
        rBundle = ResourceBundle.getBundle(BUNDLE, locale);
        c.setLocaleBundle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rdbHU = new javax.swing.JRadioButton();
        rdbEN = new javax.swing.JRadioButton();
        lblList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstList = new javax.swing.JList<>();
        lblScores = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        buttonGroup1.add(rdbHU);
        rdbHU.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdbHU.setSelected(true);
        rdbHU.setText("magyar");
        rdbHU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aSource/Hungary.png"))); // NOI18N
        rdbHU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbHUActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbEN);
        rdbEN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbEN.setText("english");
        rdbEN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aSource/Great-britain.png"))); // NOI18N
        rdbEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbENActionPerformed(evt);
            }
        });

        lblList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblList.setText("jLabel1");

        lstList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstList);

        lblScores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblScores.setText("jLabel2");

        btnStart.setText("jButton2");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbHU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                        .addComponent(rdbEN))
                    .addComponent(lblScores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblScores)
                .addGap(18, 18, 18)
                .addComponent(btnStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbHU)
                    .addComponent(rdbEN))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rdbHUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbHUActionPerformed
        locale = new Locale("hu", "HU");
        rdbHU.setFont(rdbHU.getFont().deriveFont(Font.BOLD));
        rdbEN.setFont(rdbEN.getFont().deriveFont(Font.PLAIN));
        useLanguage();
    }//GEN-LAST:event_rdbHUActionPerformed

    private void rdbENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbENActionPerformed
        locale = new Locale("en", "GB");
        rdbHU.setFont(rdbHU.getFont().deriveFont(Font.PLAIN));
        rdbEN.setFont(rdbEN.getFont().deriveFont(Font.BOLD));
        useLanguage();
    }//GEN-LAST:event_rdbENActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        if (lstList.isSelectionEmpty()) {
            c.dialogNoSelection();
        } else {
            c.startBee(lstList.getSelectedIndex());
        }
        lstList.clearSelection();
    }//GEN-LAST:event_btnStartActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblList;
    private javax.swing.JLabel lblScores;
    private javax.swing.JList<String> lstList;
    private javax.swing.JRadioButton rdbEN;
    private javax.swing.JRadioButton rdbHU;
    // End of variables declaration//GEN-END:variables
}
